/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/cm150a_orig.v:2" *)
(* top =  1  *)
module CM150(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "LGSynth91/cm150a_orig.v:27" *)
  wire \[0] ;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input a;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input b;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input c;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input d;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input e;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input f;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input g;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input h;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input i;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input j;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input k;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input l;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input m;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input n;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input o;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input p;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input q;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input r;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input s;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input t;
  (* src = "LGSynth91/cm150a_orig.v:3" *)
  input u;
  (* src = "LGSynth91/cm150a_orig.v:25" *)
  output v;
  assign _18_ = _00_ & _10_;
  assign _19_ = _01_ & s;
  assign _00_ = _05_ & _11_;
  assign _20_ = _02_ & r;
  assign _01_ = _06_ & _12_;
  assign _21_ = _07_ & _13_;
  assign _02_ = h & _14_;
  assign _22_ = c & r;
  assign _03_ = _08_ & _15_;
  assign _23_ = _09_ & _16_;
  assign _04_ = b & _17_;
  assign _10_ = ~u;
  assign v = ~_18_;
  assign _05_ = ~_03_;
  assign _11_ = ~_19_;
  assign _06_ = ~e;
  assign _12_ = ~_20_;
  assign _07_ = ~g;
  assign _13_ = ~q;
  assign _14_ = ~_21_;
  assign _08_ = ~_04_;
  assign _15_ = ~_22_;
  assign _09_ = ~a;
  assign _16_ = ~q;
  assign _17_ = ~_23_;
  assign \[0]  = v;
endmodule
