/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/cm85a_orig.v:2" *)
(* top =  1  *)
module CM85(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  (* src = "LGSynth91/cm85a_orig.v:19" *)
  wire \[0] ;
  (* src = "LGSynth91/cm85a_orig.v:19" *)
  wire \[1] ;
  (* src = "LGSynth91/cm85a_orig.v:19" *)
  wire \[2] ;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input a;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input b;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input c;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input d;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input e;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input f;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input g;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input h;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input i;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input j;
  (* src = "LGSynth91/cm85a_orig.v:3" *)
  input k;
  (* src = "LGSynth91/cm85a_orig.v:15" *)
  output l;
  (* src = "LGSynth91/cm85a_orig.v:15" *)
  output m;
  (* src = "LGSynth91/cm85a_orig.v:15" *)
  output n;
  assign _32_ = _08_ & _06_;
  assign _00_ = _01_ & _02_;
  assign _01_ = _09_ & _21_;
  assign _33_ = _10_ & d;
  assign _34_ = e & _22_;
  assign _24_ = _11_ & _23_;
  assign _02_ = b & _24_;
  assign _25_ = _04_ & _02_;
  assign _26_ = _01_ & _25_;
  assign _03_ = _12_ & _26_;
  assign _04_ = _13_ & k;
  assign _35_ = i & h;
  assign _36_ = _14_ & _27_;
  assign _05_ = _15_ & _28_;
  assign _17_ = _16_ & _00_;
  assign _37_ = k & _29_;
  assign _19_ = _17_ & _30_;
  assign _38_ = _18_ & j;
  assign m = _19_ & _31_;
  assign _39_ = _20_ & _07_;
  assign _08_ = ~_03_;
  assign l = ~_32_;
  assign _09_ = ~g;
  assign _21_ = ~f;
  assign _10_ = ~e;
  assign _22_ = ~d;
  assign _11_ = ~_33_;
  assign _23_ = ~_34_;
  assign _12_ = ~_05_;
  assign _13_ = ~j;
  assign _14_ = ~i;
  assign _27_ = ~h;
  assign _15_ = ~_35_;
  assign _28_ = ~_36_;
  assign _06_ = ~a;
  assign _16_ = ~_05_;
  assign _18_ = ~k;
  assign _29_ = ~j;
  assign _30_ = ~_37_;
  assign _31_ = ~_38_;
  assign _20_ = ~1'h0;
  assign n = ~_39_;
  assign _07_ = ~c;
  assign \[0]  = l;
  assign \[1]  = m;
  assign \[2]  = n;
endmodule
