/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/decod_orig.v:2" *)
(* top =  1  *)
module decod(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[0] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[10] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[11] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[12] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[13] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[14] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[15] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[1] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[2] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[3] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[4] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[5] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[6] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[7] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[8] ;
  (* src = "LGSynt91/decod_orig.v:26" *)
  wire \[9] ;
  (* src = "LGSynt91/decod_orig.v:3" *)
  input a;
  (* src = "LGSynt91/decod_orig.v:3" *)
  input b;
  (* src = "LGSynt91/decod_orig.v:3" *)
  input c;
  (* src = "LGSynt91/decod_orig.v:3" *)
  input d;
  (* src = "LGSynt91/decod_orig.v:3" *)
  input e;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output f;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output g;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output h;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output i;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output j;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output k;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output l;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output m;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output n;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output o;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output p;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output q;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output r;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output s;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output t;
  (* src = "LGSynt91/decod_orig.v:9" *)
  output u;
  assign _19_ = _02_ & _18_;
  assign _20_ = _03_ & _19_;
  assign m = _00_ & _20_;
  assign _00_ = a & e;
  assign _01_ = _04_ & e;
  assign _06_ = _05_ & _21_;
  assign _22_ = c & _01_;
  assign s = _06_ & _22_;
  assign _08_ = _07_ & _23_;
  assign _24_ = _01_ & b;
  assign q = _08_ & _24_;
  assign _10_ = _09_ & _25_;
  assign _26_ = _00_ & b;
  assign i = _10_ & _26_;
  assign _12_ = _11_ & _27_;
  assign _28_ = _01_ & d;
  assign t = _12_ & _28_;
  assign _29_ = _00_ & d;
  assign _30_ = c & _29_;
  assign j = _13_ & _30_;
  assign _32_ = _14_ & _31_;
  assign _33_ = _15_ & _32_;
  assign u = _01_ & _33_;
  assign _17_ = _16_ & _34_;
  assign _35_ = _00_ & d;
  assign l = _17_ & _35_;
  assign _03_ = ~b;
  assign _02_ = ~c;
  assign _18_ = ~d;
  assign _04_ = ~a;
  assign _05_ = ~b;
  assign _21_ = ~d;
  assign _07_ = ~c;
  assign _23_ = ~d;
  assign _09_ = ~c;
  assign _25_ = ~d;
  assign _11_ = ~b;
  assign _27_ = ~c;
  assign _13_ = ~b;
  assign _15_ = ~b;
  assign _14_ = ~c;
  assign _31_ = ~d;
  assign _16_ = ~b;
  assign _34_ = ~c;
  assign \[0]  = 1'h0;
  assign \[10]  = 1'h0;
  assign \[11]  = q;
  assign \[12]  = 1'h0;
  assign \[13]  = s;
  assign \[14]  = t;
  assign \[15]  = u;
  assign \[1]  = 1'h0;
  assign \[2]  = 1'h0;
  assign \[3]  = i;
  assign \[4]  = j;
  assign \[5]  = 1'h0;
  assign \[6]  = l;
  assign \[7]  = m;
  assign \[8]  = 1'h0;
  assign \[9]  = 1'h0;
  assign f = 1'h0;
  assign g = 1'h0;
  assign h = 1'h0;
  assign k = 1'h0;
  assign n = 1'h0;
  assign o = 1'h0;
  assign p = 1'h0;
  assign r = 1'h0;
endmodule
