/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "cmlexamples/cm152a_orig.v:2" *)
(* top =  1  *)
module mux_cl(a, b, c, d, e, f, g, h, i, j, k, l);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "cmlexamples/cm152a_orig.v:17" *)
  wire \[0] ;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input a;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input b;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input c;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input d;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input e;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input f;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input g;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input h;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input i;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input j;
  (* src = "cmlexamples/cm152a_orig.v:3" *)
  input k;
  (* src = "cmlexamples/cm152a_orig.v:15" *)
  output l;
  assign _05_ = _03_ & _09_;
  assign _10_ = _04_ & 1'h0;
  assign _16_ = _05_ & _10_;
  assign _06_ = k & h;
  assign _11_ = i & j;
  assign _00_ = _06_ & _11_;
  assign _12_ = k & g;
  assign _13_ = j & _12_;
  assign _01_ = _07_ & _13_;
  assign _14_ = i & f;
  assign _15_ = k & _14_;
  assign _02_ = _08_ & _15_;
  assign _04_ = ~_00_;
  assign _03_ = ~_01_;
  assign _09_ = ~_02_;
  assign l = ~_16_;
  assign _07_ = ~i;
  assign _08_ = ~j;
  assign \[0]  = l;
endmodule
