/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/sct_orig.v:2" *)
(* top =  1  *)
module sct(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[0] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[10] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[12] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[14] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[1] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[2] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[3] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[4] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[5] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[6] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[7] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[8] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[9] ;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input a;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output a0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input b;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output b0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input c;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output c0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input d;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output d0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input e;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output e0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input f;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output f0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input g;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output g0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input h;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output h0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input i;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input j;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input k;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input l;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input m;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input n;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input o;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input p;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input q;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input r;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input s;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output t;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output u;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output v;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output w;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output x;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output y;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output z;
  assign _035_ = _012_ & s;
  assign _047_ = e & f;
  assign _048_ = _013_ & _035_;
  assign u = _014_ & _036_;
  assign h0 = e & r;
  assign _049_ = c & b;
  assign t = _015_ & _037_;
  assign _050_ = _016_ & _038_;
  assign w = _000_ & _039_;
  assign _000_ = _017_ & e;
  assign _051_ = h & g;
  assign _040_ = i & _001_;
  assign x = _018_ & _040_;
  assign _001_ = _019_ & e;
  assign _022_ = _020_ & _041_;
  assign _042_ = _021_ & e;
  assign _052_ = _022_ & _042_;
  assign _002_ = d & _003_;
  assign _003_ = _023_ & q;
  assign _053_ = _024_ & j;
  assign _054_ = _025_ & _043_;
  assign _044_ = h & i;
  assign _004_ = g & _044_;
  assign _045_ = _026_ & _005_;
  assign _055_ = _027_ & _045_;
  assign _005_ = _028_ & e;
  assign _006_ = d & _007_;
  assign _007_ = _029_ & q;
  assign _056_ = _030_ & _008_;
  assign _008_ = _031_ & e;
  assign _009_ = d & _010_;
  assign _010_ = _032_ & q;
  assign _057_ = _033_ & _046_;
  assign _011_ = _034_ & 1'h0;
  assign f0 = d & e;
  assign _012_ = ~p;
  assign _013_ = ~f;
  assign _014_ = ~_047_;
  assign _036_ = ~_048_;
  assign _015_ = ~o;
  assign _037_ = ~_049_;
  assign _016_ = ~g;
  assign _038_ = ~h;
  assign _039_ = ~_050_;
  assign _017_ = ~q;
  assign _018_ = ~_051_;
  assign _019_ = ~q;
  assign _021_ = ~_002_;
  assign _020_ = ~k;
  assign _041_ = ~1'h0;
  assign z = ~_052_;
  assign _023_ = ~1'h0;
  assign _024_ = ~_004_;
  assign _025_ = ~1'h0;
  assign _043_ = ~_053_;
  assign y = ~_054_;
  assign _026_ = ~l;
  assign _027_ = ~1'h0;
  assign a0 = ~_055_;
  assign _028_ = ~_006_;
  assign _029_ = ~1'h0;
  assign _030_ = ~1'h0;
  assign b0 = ~_056_;
  assign _031_ = ~_009_;
  assign _032_ = ~1'h0;
  assign _033_ = ~1'h0;
  assign _046_ = ~_011_;
  assign d0 = ~_057_;
  assign _034_ = ~q;
  assign c0 = ~1'h0;
  assign \[0]  = t;
  assign \[10]  = d0;
  assign \[12]  = f0;
  assign \[14]  = h0;
  assign \[1]  = u;
  assign \[2]  = 1'h0;
  assign \[3]  = w;
  assign \[4]  = x;
  assign \[5]  = y;
  assign \[6]  = z;
  assign \[7]  = a0;
  assign \[8]  = b0;
  assign \[9]  = c0;
  assign e0 = c;
  assign g0 = e;
  assign v = 1'h0;
endmodule
