/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/sct_orig.v:2" *)
(* top =  1  *)
module sct(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[0] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[10] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[12] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[14] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[1] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[2] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[3] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[4] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[5] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[6] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[7] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[8] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[9] ;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input a;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output a0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input b;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output b0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input c;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output c0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input d;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output d0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input e;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output e0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input f;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output f0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input g;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output g0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input h;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output h0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input i;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input j;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input k;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input l;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input m;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input n;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input o;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input p;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input q;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input r;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input s;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output t;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output u;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output v;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output w;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output x;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output y;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output z;
  assign _33_ = e & f;
  assign _34_ = _08_ & s;
  assign u = _09_ & _25_;
  assign h0 = e & r;
  assign _35_ = c & b;
  assign t = _10_ & _26_;
  assign _36_ = _11_ & _27_;
  assign w = _00_ & _28_;
  assign _00_ = _12_ & e;
  assign x = i & _01_;
  assign _01_ = _13_ & e;
  assign _16_ = _14_ & _29_;
  assign _30_ = _15_ & e;
  assign _37_ = _16_ & _30_;
  assign _02_ = d & _03_;
  assign _03_ = _17_ & q;
  assign _38_ = _18_ & j;
  assign _39_ = _19_ & _31_;
  assign _40_ = _20_ & _04_;
  assign _04_ = _21_ & e;
  assign _05_ = d & _06_;
  assign _06_ = _22_ & q;
  assign _41_ = _23_ & _32_;
  assign _07_ = _24_ & 1'h0;
  assign f0 = d & e;
  assign _08_ = ~p;
  assign _09_ = ~_33_;
  assign _25_ = ~_34_;
  assign _10_ = ~o;
  assign _26_ = ~_35_;
  assign _11_ = ~g;
  assign _27_ = ~h;
  assign _28_ = ~_36_;
  assign _12_ = ~q;
  assign _13_ = ~q;
  assign _15_ = ~_02_;
  assign _14_ = ~k;
  assign _29_ = ~1'h0;
  assign z = ~_37_;
  assign _17_ = ~1'h0;
  assign _18_ = ~1'h0;
  assign _19_ = ~1'h0;
  assign _31_ = ~_38_;
  assign y = ~_39_;
  assign a0 = ~1'h0;
  assign _20_ = ~1'h0;
  assign b0 = ~_40_;
  assign _21_ = ~_05_;
  assign _22_ = ~1'h0;
  assign _23_ = ~1'h0;
  assign _32_ = ~_07_;
  assign d0 = ~_41_;
  assign _24_ = ~q;
  assign c0 = ~1'h0;
  assign \[0]  = t;
  assign \[10]  = d0;
  assign \[12]  = f0;
  assign \[14]  = h0;
  assign \[1]  = u;
  assign \[2]  = 1'h0;
  assign \[3]  = w;
  assign \[4]  = x;
  assign \[5]  = y;
  assign \[6]  = z;
  assign \[7]  = a0;
  assign \[8]  = b0;
  assign \[9]  = c0;
  assign e0 = c;
  assign g0 = e;
  assign v = 1'h0;
endmodule
