/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/sct_orig.v:2" *)
(* top =  1  *)
module sct(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[0] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[10] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[12] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[14] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[1] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[2] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[3] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[4] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[5] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[6] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[7] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[8] ;
  (* src = "LGSynt91/sct_orig.v:39" *)
  wire \[9] ;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input a;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output a0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input b;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output b0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input c;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output c0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input d;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output d0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input e;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output e0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input f;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output f0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input g;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output g0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input h;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output h0;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input i;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input j;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input k;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input l;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input m;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input n;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input o;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input p;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input q;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input r;
  (* src = "LGSynt91/sct_orig.v:3" *)
  input s;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output t;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output u;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output v;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output w;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output x;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output y;
  (* src = "LGSynt91/sct_orig.v:23" *)
  output z;
  assign _083_ = _018_ & _012_;
  assign _012_ = _019_ & e;
  assign _013_ = d & _014_;
  assign _014_ = _020_ & q;
  assign _084_ = _021_ & c;
  assign _085_ = _017_ & _052_;
  assign _086_ = _022_ & _053_;
  assign _087_ = _023_ & _054_;
  assign _056_ = _024_ & _055_;
  assign _015_ = 1'h0 & _056_;
  assign _088_ = c & _057_;
  assign _016_ = q & _058_;
  assign _059_ = q & e;
  assign _017_ = o & _059_;
  assign _089_ = _025_ & q;
  assign _090_ = _026_ & _060_;
  assign f0 = e & _061_;
  assign _062_ = _027_ & s;
  assign _091_ = e & f;
  assign _092_ = _028_ & _062_;
  assign u = _029_ & _063_;
  assign h0 = e & r;
  assign _093_ = o & _064_;
  assign _094_ = c & b;
  assign t = _030_ & _065_;
  assign _066_ = _031_ & e;
  assign _095_ = _032_ & _066_;
  assign _096_ = _033_ & _067_;
  assign _097_ = _034_ & _068_;
  assign w = _000_ & _069_;
  assign _000_ = _035_ & e;
  assign _071_ = h & g;
  assign _098_ = _036_ & _070_;
  assign _099_ = i & _071_;
  assign _073_ = _001_ & _072_;
  assign x = _037_ & _073_;
  assign _001_ = _038_ & e;
  assign _041_ = _039_ & _074_;
  assign _075_ = _040_ & e;
  assign _100_ = _041_ & _075_;
  assign _101_ = _042_ & _076_;
  assign _002_ = _003_ & _077_;
  assign _003_ = d & _004_;
  assign _004_ = _043_ & q;
  assign _005_ = _044_ & _078_;
  assign _006_ = _045_ & q;
  assign _102_ = _046_ & j;
  assign _103_ = _047_ & _079_;
  assign _080_ = h & i;
  assign _007_ = g & _080_;
  assign _081_ = _048_ & _008_;
  assign _104_ = _049_ & _081_;
  assign _008_ = _050_ & e;
  assign _009_ = d & _010_;
  assign _010_ = _051_ & q;
  assign _105_ = _007_ & _005_;
  assign _011_ = l & _082_;
  assign _082_ = ~_105_;
  assign _018_ = ~_006_;
  assign b0 = ~_083_;
  assign _019_ = ~_013_;
  assign _020_ = ~1'h0;
  assign _021_ = ~d;
  assign _022_ = ~_015_;
  assign _052_ = ~_084_;
  assign _053_ = ~_085_;
  assign d0 = ~_086_;
  assign _023_ = ~a;
  assign _054_ = ~1'h0;
  assign _024_ = ~_016_;
  assign _055_ = ~_087_;
  assign _057_ = ~d;
  assign _058_ = ~_088_;
  assign c0 = ~1'h0;
  assign _025_ = ~c;
  assign _026_ = ~d;
  assign _060_ = ~_089_;
  assign _061_ = ~_090_;
  assign _027_ = ~p;
  assign _028_ = ~f;
  assign _029_ = ~_091_;
  assign _063_ = ~_092_;
  assign _064_ = ~b;
  assign _030_ = ~_093_;
  assign _065_ = ~_094_;
  assign _032_ = ~g;
  assign _031_ = ~q;
  assign _033_ = ~1'h0;
  assign _067_ = ~_095_;
  assign v = ~_096_;
  assign _034_ = ~g;
  assign _068_ = ~h;
  assign _069_ = ~_097_;
  assign _035_ = ~q;
  assign _036_ = ~i;
  assign _070_ = ~_071_;
  assign _037_ = ~_098_;
  assign _072_ = ~_099_;
  assign _038_ = ~q;
  assign _040_ = ~_002_;
  assign _039_ = ~k;
  assign _074_ = ~_006_;
  assign z = ~_100_;
  assign _042_ = ~d;
  assign _076_ = ~_005_;
  assign _077_ = ~_101_;
  assign _043_ = ~1'h0;
  assign _044_ = ~j;
  assign _078_ = ~k;
  assign _045_ = ~c;
  assign _046_ = ~_007_;
  assign _047_ = ~1'h0;
  assign _079_ = ~_102_;
  assign y = ~_103_;
  assign _048_ = ~_011_;
  assign _049_ = ~_006_;
  assign a0 = ~_104_;
  assign _050_ = ~_009_;
  assign _051_ = ~1'h0;
  assign \[0]  = t;
  assign \[10]  = d0;
  assign \[12]  = f0;
  assign \[14]  = h0;
  assign \[1]  = u;
  assign \[2]  = v;
  assign \[3]  = w;
  assign \[4]  = x;
  assign \[5]  = y;
  assign \[6]  = z;
  assign \[7]  = a0;
  assign \[8]  = b0;
  assign \[9]  = c0;
  assign e0 = c;
  assign g0 = e;
endmodule
