/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/pcle_orig.v:2" *)
(* top =  1  *)
module pcle_cl(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[0] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[1] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[2] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[3] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[4] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[5] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[6] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[7] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[8] ;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input a;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output a0;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input b;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output b0;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input c;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input d;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input e;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input f;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input g;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input h;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input i;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input j;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input k;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input l;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input m;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input n;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input o;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input p;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input q;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input r;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input s;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output t;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output u;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output v;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output w;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output x;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output y;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output z;
  assign _03_ = _00_ & 1'h0;
  assign _04_ = i & a;
  assign _05_ = _01_ & _02_;
  assign _00_ = ~l;
  assign _01_ = ~_03_;
  assign _02_ = ~_04_;
  assign u = ~_05_;
  assign \[0]  = 1'h0;
  assign \[1]  = u;
  assign \[2]  = 1'h0;
  assign \[3]  = 1'h0;
  assign \[4]  = 1'h0;
  assign \[5]  = 1'h0;
  assign \[6]  = 1'h0;
  assign \[7]  = 1'h0;
  assign \[8]  = 1'h0;
  assign a0 = 1'h0;
  assign b0 = 1'h0;
  assign t = 1'h0;
  assign v = 1'h0;
  assign w = 1'h0;
  assign x = 1'h0;
  assign y = 1'h0;
  assign z = 1'h0;
endmodule
