/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/pcle_orig.v:2" *)
(* top =  1  *)
module pcle_cl(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[0] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[1] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[2] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[3] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[4] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[5] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[6] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[7] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[8] ;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input a;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output a0;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input b;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output b0;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input c;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input d;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input e;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input f;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input g;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input h;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input i;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input j;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input k;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input l;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input m;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input n;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input o;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input p;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input q;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input r;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input s;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output t;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output u;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output v;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output w;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output x;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output y;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output z;
  assign _057_ = _010_ & _031_;
  assign _058_ = _000_ & _032_;
  assign _059_ = _011_ & _033_;
  assign _034_ = _012_ & j;
  assign _000_ = _013_ & _034_;
  assign _001_ = i & g;
  assign _060_ = _014_ & _035_;
  assign _061_ = _000_ & _036_;
  assign _062_ = _015_ & _037_;
  assign _002_ = i & h;
  assign _063_ = _016_ & m;
  assign _064_ = l & _038_;
  assign _065_ = _017_ & _039_;
  assign _066_ = _000_ & _040_;
  assign _067_ = _018_ & _041_;
  assign _003_ = i & b;
  assign _068_ = _019_ & _000_;
  assign _069_ = i & a;
  assign _070_ = _020_ & _042_;
  assign _071_ = _021_ & n;
  assign _072_ = _004_ & _043_;
  assign _073_ = _022_ & _044_;
  assign _074_ = _000_ & _045_;
  assign _075_ = _023_ & _046_;
  assign _004_ = l & m;
  assign _005_ = i & c;
  assign _076_ = _024_ & o;
  assign _077_ = _006_ & _047_;
  assign _078_ = _025_ & _048_;
  assign _079_ = _000_ & _049_;
  assign _080_ = _026_ & _050_;
  assign _006_ = _004_ & n;
  assign _007_ = i & d;
  assign _081_ = _027_ & _051_;
  assign _082_ = _000_ & _052_;
  assign _083_ = _028_ & _053_;
  assign _008_ = i & e;
  assign _084_ = _029_ & _054_;
  assign _085_ = _000_ & _055_;
  assign _086_ = _030_ & _056_;
  assign _009_ = i & f;
  assign _011_ = ~_001_;
  assign _010_ = ~1'h0;
  assign _031_ = ~r;
  assign _032_ = ~_057_;
  assign _033_ = ~_058_;
  assign a0 = ~_059_;
  assign _012_ = ~k;
  assign _013_ = ~i;
  assign _015_ = ~_002_;
  assign _014_ = ~1'h0;
  assign _035_ = ~s;
  assign _036_ = ~_060_;
  assign _037_ = ~_061_;
  assign b0 = ~_062_;
  assign _018_ = ~_003_;
  assign _016_ = ~l;
  assign _038_ = ~m;
  assign _017_ = ~_063_;
  assign _039_ = ~_064_;
  assign _040_ = ~_065_;
  assign _041_ = ~_066_;
  assign v = ~_067_;
  assign _019_ = ~l;
  assign _020_ = ~_068_;
  assign _042_ = ~_069_;
  assign u = ~_070_;
  assign _023_ = ~_005_;
  assign _021_ = ~_004_;
  assign _043_ = ~n;
  assign _022_ = ~_071_;
  assign _044_ = ~_072_;
  assign _045_ = ~_073_;
  assign _046_ = ~_074_;
  assign w = ~_075_;
  assign _026_ = ~_007_;
  assign _024_ = ~_006_;
  assign _047_ = ~o;
  assign _025_ = ~_076_;
  assign _048_ = ~_077_;
  assign _049_ = ~_078_;
  assign _050_ = ~_079_;
  assign x = ~_080_;
  assign _028_ = ~_008_;
  assign _027_ = ~1'h0;
  assign _051_ = ~p;
  assign _052_ = ~_081_;
  assign _053_ = ~_082_;
  assign y = ~_083_;
  assign _030_ = ~_009_;
  assign _029_ = ~1'h0;
  assign _054_ = ~q;
  assign _055_ = ~_084_;
  assign _056_ = ~_085_;
  assign z = ~_086_;
  assign \[0]  = 1'h0;
  assign \[1]  = u;
  assign \[2]  = v;
  assign \[3]  = w;
  assign \[4]  = x;
  assign \[5]  = y;
  assign \[6]  = z;
  assign \[7]  = a0;
  assign \[8]  = b0;
  assign t = 1'h0;
endmodule
