/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/pcle_orig.v:2" *)
(* top =  1  *)
module pcle_cl(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[0] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[1] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[2] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[3] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[4] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[5] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[6] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[7] ;
  (* src = "LGSynt91/pcle_orig.v:33" *)
  wire \[8] ;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input a;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output a0;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input b;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output b0;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input c;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input d;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input e;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input f;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input g;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input h;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input i;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input j;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input k;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input l;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input m;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input n;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input o;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input p;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input q;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input r;
  (* src = "LGSynt91/pcle_orig.v:3" *)
  input s;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output t;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output u;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output v;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output w;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output x;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output y;
  (* src = "LGSynt91/pcle_orig.v:23" *)
  output z;
  assign b0 = i & h;
  assign _047_ = _009_ & _026_;
  assign _048_ = _000_ & _027_;
  assign _049_ = _010_ & _028_;
  assign _002_ = i & b;
  assign _050_ = _011_ & _000_;
  assign _051_ = i & a;
  assign _052_ = _012_ & _029_;
  assign _053_ = _013_ & n;
  assign _054_ = _003_ & _030_;
  assign _055_ = _014_ & _031_;
  assign _056_ = _000_ & _032_;
  assign _057_ = _015_ & _033_;
  assign _003_ = l & m;
  assign _004_ = i & c;
  assign _058_ = _016_ & _034_;
  assign _059_ = _000_ & _035_;
  assign _060_ = _017_ & _036_;
  assign _005_ = _003_ & n;
  assign _006_ = i & d;
  assign _061_ = _018_ & _037_;
  assign _062_ = _000_ & _038_;
  assign _063_ = _019_ & _039_;
  assign _007_ = i & e;
  assign _064_ = _020_ & _040_;
  assign _065_ = _000_ & _041_;
  assign _066_ = _021_ & _042_;
  assign _008_ = i & f;
  assign _067_ = _022_ & _043_;
  assign _068_ = _000_ & _044_;
  assign _069_ = _023_ & _045_;
  assign _046_ = _024_ & j;
  assign _000_ = _025_ & _046_;
  assign _001_ = i & g;
  assign _010_ = ~_002_;
  assign _009_ = ~l;
  assign _026_ = ~m;
  assign _027_ = ~_047_;
  assign _028_ = ~_048_;
  assign v = ~_049_;
  assign _011_ = ~l;
  assign _012_ = ~_050_;
  assign _029_ = ~_051_;
  assign u = ~_052_;
  assign _015_ = ~_004_;
  assign _013_ = ~_003_;
  assign _030_ = ~n;
  assign _014_ = ~_053_;
  assign _031_ = ~_054_;
  assign _032_ = ~_055_;
  assign _033_ = ~_056_;
  assign w = ~_057_;
  assign _017_ = ~_006_;
  assign _016_ = ~_005_;
  assign _034_ = ~o;
  assign _035_ = ~_058_;
  assign _036_ = ~_059_;
  assign x = ~_060_;
  assign _019_ = ~_007_;
  assign _018_ = ~1'h0;
  assign _037_ = ~p;
  assign _038_ = ~_061_;
  assign _039_ = ~_062_;
  assign y = ~_063_;
  assign _021_ = ~_008_;
  assign _020_ = ~1'h0;
  assign _040_ = ~q;
  assign _041_ = ~_064_;
  assign _042_ = ~_065_;
  assign z = ~_066_;
  assign _023_ = ~_001_;
  assign _022_ = ~1'h0;
  assign _043_ = ~r;
  assign _044_ = ~_067_;
  assign _045_ = ~_068_;
  assign a0 = ~_069_;
  assign _024_ = ~k;
  assign _025_ = ~i;
  assign \[0]  = 1'h0;
  assign \[1]  = u;
  assign \[2]  = v;
  assign \[3]  = w;
  assign \[4]  = x;
  assign \[5]  = y;
  assign \[6]  = z;
  assign \[7]  = a0;
  assign \[8]  = b0;
  assign t = 1'h0;
endmodule
