/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/cmb_orig.v:2" *)
(* top =  1  *)
module cmb(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[0] ;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[1] ;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[2] ;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[3] ;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input a;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input b;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input c;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input d;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input e;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input f;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input g;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input h;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input i;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input j;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input k;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input l;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input m;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input n;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input o;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input p;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output q;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output r;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output s;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output t;
  assign _018_ = _000_ & l;
  assign _052_ = j & k;
  assign q = _018_ & _052_;
  assign _019_ = _001_ & b;
  assign _053_ = _002_ & a;
  assign _000_ = _019_ & _053_;
  assign _020_ = g & f;
  assign _054_ = h & i;
  assign _001_ = _020_ & _054_;
  assign _055_ = e & d;
  assign _002_ = c & _055_;
  assign _086_ = _021_ & _011_;
  assign _087_ = _022_ & _056_;
  assign _058_ = _023_ & _057_;
  assign _059_ = _024_ & _058_;
  assign _003_ = _004_ & _059_;
  assign _027_ = _025_ & _060_;
  assign _062_ = _026_ & _061_;
  assign _004_ = _027_ & _062_;
  assign _088_ = l & _063_;
  assign _065_ = _028_ & _064_;
  assign _089_ = _007_ & _065_;
  assign _006_ = _029_ & e;
  assign _090_ = _030_ & _066_;
  assign _091_ = m & n;
  assign _092_ = _031_ & m;
  assign _093_ = _032_ & _067_;
  assign _007_ = _033_ & _068_;
  assign _008_ = _034_ & k;
  assign _009_ = _035_ & j;
  assign _010_ = _036_ & i;
  assign _070_ = _037_ & _069_;
  assign _094_ = _038_ & _070_;
  assign _095_ = _004_ & _071_;
  assign _072_ = _039_ & e;
  assign _012_ = _040_ & _072_;
  assign _073_ = f & e;
  assign _013_ = _041_ & _073_;
  assign _074_ = g & f;
  assign _014_ = e & _074_;
  assign _096_ = _042_ & _011_;
  assign _097_ = o & _075_;
  assign _077_ = _043_ & _076_;
  assign _078_ = _044_ & _077_;
  assign t = _015_ & _078_;
  assign _046_ = _045_ & _079_;
  assign _080_ = _016_ & _017_;
  assign _015_ = _046_ & _080_;
  assign _049_ = _047_ & _081_;
  assign _083_ = _048_ & _082_;
  assign _016_ = _049_ & _083_;
  assign _085_ = _050_ & _084_;
  assign _017_ = _051_ & _085_;
  assign _021_ = ~_003_;
  assign _022_ = ~p;
  assign _056_ = ~_086_;
  assign r = ~_087_;
  assign _024_ = ~g;
  assign _023_ = ~h;
  assign _057_ = ~f;
  assign _026_ = ~_005_;
  assign _025_ = ~_008_;
  assign _060_ = ~_009_;
  assign _061_ = ~_010_;
  assign _063_ = ~k;
  assign _028_ = ~_006_;
  assign _064_ = ~_088_;
  assign _005_ = ~_089_;
  assign _029_ = ~p;
  assign _031_ = ~l;
  assign _030_ = ~o;
  assign _066_ = ~n;
  assign _032_ = ~_090_;
  assign _067_ = ~_091_;
  assign _033_ = ~_092_;
  assign _068_ = ~_093_;
  assign _034_ = ~j;
  assign _035_ = ~i;
  assign _036_ = ~h;
  assign _038_ = ~_012_;
  assign _037_ = ~_013_;
  assign _069_ = ~_014_;
  assign _071_ = ~_094_;
  assign _011_ = ~_095_;
  assign _039_ = ~g;
  assign _040_ = ~h;
  assign _041_ = ~h;
  assign _042_ = ~_003_;
  assign _075_ = ~_096_;
  assign s = ~_097_;
  assign _044_ = ~p;
  assign _043_ = ~n;
  assign _076_ = ~o;
  assign _045_ = ~f;
  assign _079_ = ~e;
  assign _048_ = ~j;
  assign _047_ = ~k;
  assign _081_ = ~l;
  assign _082_ = ~m;
  assign _051_ = ~g;
  assign _050_ = ~h;
  assign _084_ = ~i;
  assign \[0]  = q;
  assign \[1]  = r;
  assign \[2]  = s;
  assign \[3]  = t;
endmodule
