/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/cmb_orig.v:2" *)
(* top =  1  *)
module cmb(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[0] ;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[1] ;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[2] ;
  (* src = "LGSynth91/cmb_orig.v:25" *)
  wire \[3] ;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input a;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input b;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input c;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input d;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input e;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input f;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input g;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input h;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input i;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input j;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input k;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input l;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input m;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input n;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input o;
  (* src = "LGSynth91/cmb_orig.v:3" *)
  input p;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output q;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output r;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output s;
  (* src = "LGSynth91/cmb_orig.v:20" *)
  output t;
  assign _27_ = _04_ & _01_;
  assign _28_ = _05_ & _15_;
  assign _17_ = _06_ & _16_;
  assign _18_ = _07_ & _17_;
  assign _00_ = 1'h0 & _18_;
  assign _29_ = _08_ & _01_;
  assign _30_ = o & _19_;
  assign _21_ = _09_ & _20_;
  assign _22_ = _10_ & _21_;
  assign t = _02_ & _22_;
  assign _12_ = _11_ & _23_;
  assign _24_ = 1'h0 & _03_;
  assign _02_ = _12_ & _24_;
  assign _26_ = _13_ & _25_;
  assign _03_ = _14_ & _26_;
  assign _04_ = ~_00_;
  assign _05_ = ~p;
  assign _15_ = ~_27_;
  assign r = ~_28_;
  assign _07_ = ~g;
  assign _06_ = ~h;
  assign _16_ = ~f;
  assign _01_ = ~1'h0;
  assign _08_ = ~_00_;
  assign _19_ = ~_29_;
  assign s = ~_30_;
  assign _10_ = ~p;
  assign _09_ = ~n;
  assign _20_ = ~o;
  assign _11_ = ~f;
  assign _23_ = ~e;
  assign _14_ = ~g;
  assign _13_ = ~h;
  assign _25_ = ~i;
  assign \[0]  = 1'h0;
  assign \[1]  = r;
  assign \[2]  = s;
  assign \[3]  = t;
  assign q = 1'h0;
endmodule
