/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/x4_orig.v:2" *)
(* top =  1  *)
module x4(a, b, g, h, i, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, a3, b3, c3, d3, e3, f3, g3, h3, i3, j3, k3, l3, m3, n3, o3, p3, q3, r3, s3, t3, u3, v3, w3, x3, y3, z3, a4, b4, c4, d4, e4, f4, g4, h4, i4, j4, k4, l4, m4, n4, o4, p4, q4, r4, s4, t4, u4, v4, w4, x4, y4, z4, a5, b5, c5, d5, e5, f5, g5, h5, i5, j5, k5, l5, m5, n5, o5);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[0] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[10] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[11] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[12] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[13] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[14] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[15] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[16] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[17] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[18] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[19] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[1] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[20] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[21] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[22] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[23] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[24] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[25] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[26] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[27] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[28] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[29] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[2] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[30] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[31] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[32] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[33] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[34] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[35] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[36] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[37] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[38] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[39] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[3] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[40] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[41] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[42] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[43] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[44] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[45] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[46] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[47] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[48] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[49] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[4] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[50] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[51] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[52] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[53] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[54] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[55] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[56] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[57] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[58] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[59] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[5] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[60] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[61] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[62] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[63] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[64] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[65] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[66] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[67] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[68] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[69] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[6] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[70] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[7] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[8] ;
  (* src = "LGSynt91/x4_orig.v:170" *)
  wire \[9] ;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input a;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input a0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input a1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input a2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output a3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output a4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output a5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input b;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input b0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input b1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input b2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output b3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output b4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output b5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input c0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input c1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input c2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output c3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output c4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output c5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input d0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input d1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input d2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output d3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output d4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output d5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input e0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input e1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input e2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output e3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output e4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output e5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input f0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input f1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input f2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output f3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output f4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output f5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input g;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input g0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input g1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input g2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output g3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output g4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output g5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input h;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input h0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input h1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input h2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output h3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output h4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output h5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input i;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input i0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input i1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input i2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output i3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output i4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output i5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input j1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input j2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output j3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output j4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output j5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input k;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input k0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input k1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input k2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output k3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output k4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output k5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input l;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input l0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input l1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input l2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output l3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output l4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output l5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input m;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input m0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input m1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input m2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output m3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output m4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output m5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input n;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input n0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input n1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input n2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output n3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output n4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output n5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input o;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input o0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input o1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input o2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output o3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output o4;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output o5;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input p;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input p0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input p1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input p2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output p3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output p4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input q;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input q0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input q1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input q2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output q3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output q4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input r;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input r0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input r1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input r2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output r3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output r4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input s;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input s0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input s1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input s2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output s3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output s4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input t;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input t0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input t1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input t2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output t3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output t4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input u;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input u0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input u1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input u2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output u3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output u4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input v;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input v0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input v1;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input v2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output v3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output v4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input w;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input w0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input w1;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output w2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output w3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output w4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input x;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input x0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input x1;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output x2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output x3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output x4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input y;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input y0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input y1;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output y2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output y3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output y4;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input z;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input z0;
  (* src = "LGSynt91/x4_orig.v:3" *)
  input z1;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output z2;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output z3;
  (* src = "LGSynt91/x4_orig.v:98" *)
  output z4;
  assign _167_ = _003_ & l2;
  assign _293_ = _002_ & _167_;
  assign _000_ = _001_ & _168_;
  assign _294_ = k2 & l2;
  assign _170_ = _002_ & _169_;
  assign _295_ = u2 & _170_;
  assign _296_ = _064_ & l2;
  assign _297_ = _065_ & _171_;
  assign _002_ = _066_ & _172_;
  assign _003_ = _067_ & _173_;
  assign _298_ = l2 & m2;
  assign _175_ = _005_ & _174_;
  assign _299_ = u2 & _175_;
  assign _300_ = _068_ & l2;
  assign _301_ = _069_ & _176_;
  assign _178_ = _070_ & _177_;
  assign _005_ = _071_ & _178_;
  assign _180_ = _072_ & _179_;
  assign _302_ = _073_ & _180_;
  assign _303_ = 1'h0 & _181_;
  assign _182_ = l2 & m2;
  assign _007_ = _074_ & _182_;
  assign _304_ = _075_ & _008_;
  assign _183_ = _014_ & e1;
  assign _305_ = _012_ & _183_;
  assign _008_ = _009_ & _184_;
  assign _185_ = _012_ & _007_;
  assign _306_ = _076_ & _185_;
  assign _009_ = _010_ & _186_;
  assign _307_ = _077_ & _187_;
  assign _308_ = _012_ & _188_;
  assign _010_ = _011_ & _189_;
  assign _309_ = _078_ & _190_;
  assign _012_ = _079_ & _191_;
  assign _192_ = _080_ & o2;
  assign _310_ = _081_ & _192_;
  assign _013_ = _082_ & d1;
  assign _194_ = _083_ & _193_;
  assign _014_ = _084_ & _194_;
  assign _311_ = _085_ & 1'h0;
  assign _015_ = p2 & _195_;
  assign _312_ = _086_ & _196_;
  assign _313_ = n1 & _197_;
  assign _314_ = _017_ & _198_;
  assign _199_ = _087_ & e1;
  assign _016_ = _088_ & _199_;
  assign _315_ = _089_ & e1;
  assign _201_ = _090_ & _200_;
  assign _316_ = b1 & _201_;
  assign _204_ = s2 & l1;
  assign _317_ = _091_ & _202_;
  assign _093_ = _092_ & _203_;
  assign _318_ = t2 & _204_;
  assign m5 = _093_ & _205_;
  assign _319_ = 1'h0 & _019_;
  assign _320_ = _018_ & _206_;
  assign _019_ = u2 & _207_;
  assign _321_ = _094_ & v2;
  assign _322_ = _095_ & _208_;
  assign o5 = f4 & _209_;
  assign _020_ = 1'h0 & r2;
  assign _021_ = _096_ & _210_;
  assign _323_ = _097_ & _211_;
  assign _212_ = _023_ & g0;
  assign _213_ = v2 & _212_;
  assign _022_ = _098_ & _213_;
  assign _324_ = m1 & _214_;
  assign _023_ = _024_ & _215_;
  assign _217_ = _099_ & _216_;
  assign _325_ = _100_ & _217_;
  assign _326_ = m1 & _218_;
  assign _327_ = f0 & v2;
  assign _328_ = _101_ & _219_;
  assign _025_ = _102_ & _220_;
  assign _329_ = _103_ & _221_;
  assign _330_ = _104_ & _222_;
  assign _223_ = _105_ & _027_;
  assign g3 = _106_ & _223_;
  assign _224_ = _107_ & n2;
  assign _331_ = e1 & _224_;
  assign _332_ = _108_ & _225_;
  assign _226_ = _109_ & p0;
  assign i3 = _110_ & _226_;
  assign n3 = _111_ & b;
  assign o3 = _112_ & a;
  assign _227_ = 1'h0 & 1'h0;
  assign _333_ = _113_ & _227_;
  assign _334_ = _028_ & _228_;
  assign _028_ = _114_ & _229_;
  assign _231_ = _115_ & _230_;
  assign _232_ = _116_ & _231_;
  assign _029_ = h0 & _232_;
  assign _335_ = _117_ & _233_;
  assign _336_ = _118_ & _234_;
  assign _337_ = _119_ & _235_;
  assign _122_ = _120_ & _236_;
  assign _237_ = _121_ & _030_;
  assign _338_ = _122_ & _237_;
  assign _339_ = _123_ & f1;
  assign _238_ = _124_ & 1'h0;
  assign _031_ = _125_ & _238_;
  assign _239_ = 1'h0 & o0;
  assign _032_ = _126_ & _239_;
  assign _240_ = v2 & g0;
  assign _241_ = m1 & _240_;
  assign _034_ = _127_ & _241_;
  assign _340_ = _128_ & _242_;
  assign _244_ = m1 & _243_;
  assign _341_ = v2 & _244_;
  assign _036_ = g & g0;
  assign _342_ = _129_ & _245_;
  assign _246_ = _130_ & p1;
  assign _343_ = _131_ & _246_;
  assign _037_ = _038_ & _247_;
  assign _344_ = _132_ & e1;
  assign _249_ = _133_ & _248_;
  assign _345_ = _134_ & _249_;
  assign _346_ = _042_ & 1'h0;
  assign _347_ = _039_ & _250_;
  assign _251_ = _040_ & p1;
  assign _348_ = _135_ & _251_;
  assign _039_ = _136_ & _252_;
  assign _253_ = 1'h0 & k;
  assign _254_ = g0 & _253_;
  assign _041_ = _137_ & _254_;
  assign _255_ = _138_ & _035_;
  assign _042_ = _139_ & _255_;
  assign _349_ = 1'h0 & l;
  assign _350_ = _044_ & q1;
  assign _043_ = _140_ & _256_;
  assign _044_ = _141_ & _040_;
  assign _257_ = _142_ & _042_;
  assign _045_ = _143_ & _257_;
  assign _351_ = 1'h0 & m;
  assign _352_ = _044_ & r1;
  assign _046_ = _144_ & _258_;
  assign _259_ = _045_ & t1;
  assign _353_ = e1 & _259_;
  assign _354_ = _047_ & _260_;
  assign _355_ = 1'h0 & n;
  assign _356_ = _044_ & s1;
  assign _047_ = _145_ & _261_;
  assign _357_ = 1'h0 & o;
  assign _358_ = _044_ & t1;
  assign _048_ = _146_ & _262_;
  assign _263_ = _045_ & v1;
  assign _359_ = e1 & _263_;
  assign _360_ = _049_ & _264_;
  assign _361_ = 1'h0 & p;
  assign _362_ = _044_ & u1;
  assign _049_ = _147_ & _265_;
  assign _363_ = 1'h0 & q;
  assign _364_ = _044_ & v1;
  assign _050_ = _148_ & _266_;
  assign _365_ = 1'h0 & r;
  assign _366_ = _044_ & w1;
  assign _051_ = _149_ & _267_;
  assign _367_ = 1'h0 & s;
  assign _368_ = _044_ & x1;
  assign _052_ = _150_ & _268_;
  assign _269_ = _045_ & z1;
  assign _369_ = e1 & _269_;
  assign _370_ = _053_ & _270_;
  assign _371_ = 1'h0 & t;
  assign _372_ = _044_ & y1;
  assign _053_ = _151_ & _271_;
  assign _272_ = _045_ & a2;
  assign _373_ = e1 & _272_;
  assign _374_ = _054_ & _273_;
  assign _375_ = 1'h0 & u;
  assign _376_ = _044_ & z1;
  assign _054_ = _152_ & _274_;
  assign _377_ = 1'h0 & v;
  assign _378_ = _044_ & a2;
  assign _055_ = _153_ & _275_;
  assign _379_ = 1'h0 & w;
  assign _380_ = _044_ & b2;
  assign _056_ = _154_ & _276_;
  assign _381_ = 1'h0 & x;
  assign _382_ = _044_ & c2;
  assign _057_ = _155_ & _277_;
  assign _278_ = _045_ & e2;
  assign _383_ = e1 & _278_;
  assign _384_ = _058_ & _279_;
  assign _385_ = 1'h0 & y;
  assign _386_ = _044_ & d2;
  assign _058_ = _156_ & _280_;
  assign _387_ = 1'h0 & z;
  assign _388_ = _044_ & e2;
  assign _059_ = _157_ & _281_;
  assign _389_ = 1'h0 & a0;
  assign _390_ = _044_ & f2;
  assign _060_ = _158_ & _282_;
  assign _391_ = 1'h0 & b0;
  assign _392_ = _044_ & g2;
  assign _061_ = _159_ & _283_;
  assign _393_ = 1'h0 & c0;
  assign _394_ = _044_ & h2;
  assign _062_ = _160_ & _284_;
  assign _285_ = _045_ & j2;
  assign _395_ = e1 & _285_;
  assign _396_ = _063_ & _286_;
  assign _397_ = 1'h0 & d0;
  assign _398_ = _044_ & i2;
  assign _063_ = _161_ & _287_;
  assign _288_ = _162_ & _040_;
  assign _399_ = j2 & _288_;
  assign _400_ = _163_ & _289_;
  assign _401_ = _164_ & _290_;
  assign _292_ = _165_ & _291_;
  assign d5 = _166_ & _292_;
  assign e5 = ~_000_;
  assign _168_ = ~_293_;
  assign _169_ = ~_294_;
  assign _001_ = ~_295_;
  assign _064_ = ~m2;
  assign _065_ = ~k2;
  assign _066_ = ~c1;
  assign _171_ = ~_296_;
  assign _172_ = ~_297_;
  assign _067_ = ~1'h0;
  assign _173_ = ~u2;
  assign f5 = ~_004_;
  assign _174_ = ~_298_;
  assign _004_ = ~_299_;
  assign _069_ = ~m2;
  assign _068_ = ~k2;
  assign _071_ = ~c1;
  assign _176_ = ~l2;
  assign _070_ = ~_300_;
  assign _177_ = ~_301_;
  assign g5 = ~_006_;
  assign _073_ = ~e1;
  assign _072_ = ~n2;
  assign _179_ = ~d1;
  assign _181_ = ~_302_;
  assign _006_ = ~_303_;
  assign _074_ = ~k2;
  assign _075_ = ~_012_;
  assign h5 = ~_304_;
  assign _184_ = ~_305_;
  assign _076_ = ~o2;
  assign _186_ = ~_306_;
  assign _077_ = ~1'h0;
  assign _187_ = ~_013_;
  assign _188_ = ~_307_;
  assign _189_ = ~_308_;
  assign _078_ = ~n2;
  assign _190_ = ~o2;
  assign _079_ = ~c1;
  assign _191_ = ~_309_;
  assign _080_ = ~c1;
  assign _081_ = ~n2;
  assign _011_ = ~_310_;
  assign _082_ = ~o2;
  assign _084_ = ~_007_;
  assign _083_ = ~e1;
  assign _193_ = ~d1;
  assign _085_ = ~_015_;
  assign i5 = ~_311_;
  assign _195_ = ~c1;
  assign j5 = ~1'h0;
  assign k5 = ~1'h0;
  assign _086_ = ~1'h0;
  assign _196_ = ~_016_;
  assign _197_ = ~_312_;
  assign _198_ = ~_313_;
  assign l5 = ~_314_;
  assign _087_ = ~m0;
  assign _088_ = ~i0;
  assign _089_ = ~m0;
  assign _090_ = ~i0;
  assign _200_ = ~_315_;
  assign _017_ = ~_316_;
  assign _092_ = ~c1;
  assign _091_ = ~t2;
  assign _202_ = ~_204_;
  assign _203_ = ~_317_;
  assign _205_ = ~_318_;
  assign _206_ = ~_319_;
  assign n5 = ~_320_;
  assign _018_ = ~_019_;
  assign _207_ = ~i0;
  assign _094_ = ~f0;
  assign _095_ = ~_020_;
  assign _208_ = ~_321_;
  assign _209_ = ~_322_;
  assign f4 = ~i0;
  assign _096_ = ~q2;
  assign _210_ = ~i;
  assign _097_ = ~_022_;
  assign _211_ = ~_025_;
  assign d3 = ~_323_;
  assign _098_ = ~c1;
  assign _214_ = ~h0;
  assign _215_ = ~_324_;
  assign _100_ = ~g;
  assign _099_ = ~h;
  assign _216_ = ~i;
  assign _218_ = ~_325_;
  assign _024_ = ~_326_;
  assign _101_ = ~k0;
  assign _102_ = ~c1;
  assign _219_ = ~_327_;
  assign _220_ = ~_328_;
  assign _103_ = ~1'h0;
  assign _221_ = ~_026_;
  assign f3 = ~_329_;
  assign _104_ = ~m0;
  assign _222_ = ~i0;
  assign _026_ = ~_330_;
  assign _105_ = ~c1;
  assign _106_ = ~i0;
  assign _107_ = ~o2;
  assign _108_ = ~n0;
  assign _225_ = ~_331_;
  assign _027_ = ~_332_;
  assign _109_ = ~c1;
  assign _110_ = ~i0;
  assign _111_ = ~i0;
  assign _112_ = ~i0;
  assign _113_ = ~_021_;
  assign _228_ = ~_333_;
  assign v3 = ~_334_;
  assign _114_ = ~1'h0;
  assign _229_ = ~i0;
  assign _116_ = ~i;
  assign _115_ = ~g;
  assign _230_ = ~h;
  assign _117_ = ~e1;
  assign _233_ = ~d1;
  assign _118_ = ~c1;
  assign _119_ = ~1'h0;
  assign _234_ = ~_335_;
  assign _235_ = ~_336_;
  assign x3 = ~_337_;
  assign _121_ = ~_031_;
  assign _120_ = ~_032_;
  assign _236_ = ~1'h0;
  assign y3 = ~_338_;
  assign _123_ = ~c1;
  assign _030_ = ~_339_;
  assign _124_ = ~1'h0;
  assign _125_ = ~c1;
  assign _126_ = ~c1;
  assign z3 = ~1'h0;
  assign a4 = ~1'h0;
  assign b4 = ~1'h0;
  assign c4 = ~1'h0;
  assign d4 = ~1'h0;
  assign g4 = ~_033_;
  assign _033_ = ~1'h0;
  assign _127_ = ~h0;
  assign _128_ = ~_036_;
  assign _242_ = ~1'h0;
  assign _243_ = ~_340_;
  assign _035_ = ~_341_;
  assign _129_ = ~_037_;
  assign _245_ = ~1'h0;
  assign h4 = ~_342_;
  assign _130_ = ~i0;
  assign _131_ = ~o1;
  assign _247_ = ~_343_;
  assign _132_ = ~m0;
  assign _133_ = ~i0;
  assign _248_ = ~o1;
  assign _134_ = ~_344_;
  assign _038_ = ~_345_;
  assign _250_ = ~_346_;
  assign i4 = ~_347_;
  assign _135_ = ~i0;
  assign _136_ = ~_041_;
  assign _252_ = ~_348_;
  assign _040_ = ~1'h0;
  assign _137_ = ~_029_;
  assign _138_ = ~_034_;
  assign _139_ = ~1'h0;
  assign j4 = ~_043_;
  assign _140_ = ~_349_;
  assign _256_ = ~_350_;
  assign _141_ = ~i0;
  assign _142_ = ~m0;
  assign _143_ = ~i0;
  assign k4 = ~_046_;
  assign _144_ = ~_351_;
  assign _258_ = ~_352_;
  assign _260_ = ~_353_;
  assign l4 = ~_354_;
  assign _145_ = ~_355_;
  assign _261_ = ~_356_;
  assign m4 = ~_048_;
  assign _146_ = ~_357_;
  assign _262_ = ~_358_;
  assign _264_ = ~_359_;
  assign n4 = ~_360_;
  assign _147_ = ~_361_;
  assign _265_ = ~_362_;
  assign o4 = ~_050_;
  assign _148_ = ~_363_;
  assign _266_ = ~_364_;
  assign p4 = ~_051_;
  assign _149_ = ~_365_;
  assign _267_ = ~_366_;
  assign q4 = ~_052_;
  assign _150_ = ~_367_;
  assign _268_ = ~_368_;
  assign _270_ = ~_369_;
  assign r4 = ~_370_;
  assign _151_ = ~_371_;
  assign _271_ = ~_372_;
  assign _273_ = ~_373_;
  assign s4 = ~_374_;
  assign _152_ = ~_375_;
  assign _274_ = ~_376_;
  assign t4 = ~_055_;
  assign _153_ = ~_377_;
  assign _275_ = ~_378_;
  assign u4 = ~_056_;
  assign _154_ = ~_379_;
  assign _276_ = ~_380_;
  assign v4 = ~_057_;
  assign _155_ = ~_381_;
  assign _277_ = ~_382_;
  assign _279_ = ~_383_;
  assign w4 = ~_384_;
  assign _156_ = ~_385_;
  assign _280_ = ~_386_;
  assign x4 = ~_059_;
  assign _157_ = ~_387_;
  assign _281_ = ~_388_;
  assign y4 = ~_060_;
  assign _158_ = ~_389_;
  assign _282_ = ~_390_;
  assign z4 = ~_061_;
  assign _159_ = ~_391_;
  assign _283_ = ~_392_;
  assign a5 = ~_062_;
  assign _160_ = ~_393_;
  assign _284_ = ~_394_;
  assign _286_ = ~_395_;
  assign b5 = ~_396_;
  assign _161_ = ~_397_;
  assign _287_ = ~_398_;
  assign _162_ = ~i0;
  assign _163_ = ~1'h0;
  assign _289_ = ~_399_;
  assign c5 = ~_400_;
  assign _164_ = ~1'h0;
  assign _290_ = ~u2;
  assign _166_ = ~c1;
  assign _165_ = ~k2;
  assign _291_ = ~_401_;
  assign w2 = ~f1;
  assign x2 = ~g1;
  assign y2 = ~h1;
  assign z2 = ~i1;
  assign a3 = ~j1;
  assign b3 = ~k1;
  assign \[0]  = w2;
  assign \[10]  = g3;
  assign \[11]  = 1'h0;
  assign \[12]  = i3;
  assign \[13]  = 1'h0;
  assign \[14]  = 1'h0;
  assign \[15]  = 1'h0;
  assign \[16]  = 1'h0;
  assign \[17]  = n3;
  assign \[18]  = o3;
  assign \[19]  = 1'h0;
  assign \[1]  = x2;
  assign \[20]  = 1'h0;
  assign \[21]  = 1'h0;
  assign \[22]  = 1'h0;
  assign \[23]  = 1'h0;
  assign \[24]  = 1'h0;
  assign \[25]  = v3;
  assign \[26]  = 1'h0;
  assign \[27]  = x3;
  assign \[28]  = y3;
  assign \[29]  = z3;
  assign \[2]  = y2;
  assign \[30]  = a4;
  assign \[31]  = b4;
  assign \[32]  = c4;
  assign \[33]  = d4;
  assign \[34]  = 1'h0;
  assign \[35]  = f4;
  assign \[36]  = g4;
  assign \[37]  = h4;
  assign \[38]  = i4;
  assign \[39]  = j4;
  assign \[3]  = z2;
  assign \[40]  = k4;
  assign \[41]  = l4;
  assign \[42]  = m4;
  assign \[43]  = n4;
  assign \[44]  = o4;
  assign \[45]  = p4;
  assign \[46]  = q4;
  assign \[47]  = r4;
  assign \[48]  = s4;
  assign \[49]  = t4;
  assign \[4]  = a3;
  assign \[50]  = u4;
  assign \[51]  = v4;
  assign \[52]  = w4;
  assign \[53]  = x4;
  assign \[54]  = y4;
  assign \[55]  = z4;
  assign \[56]  = a5;
  assign \[57]  = b5;
  assign \[58]  = c5;
  assign \[59]  = d5;
  assign \[5]  = b3;
  assign \[60]  = e5;
  assign \[61]  = f5;
  assign \[62]  = g5;
  assign \[63]  = h5;
  assign \[64]  = i5;
  assign \[65]  = j5;
  assign \[66]  = k5;
  assign \[67]  = l5;
  assign \[68]  = m5;
  assign \[69]  = n5;
  assign \[6]  = 1'h0;
  assign \[70]  = o5;
  assign \[7]  = d3;
  assign \[8]  = 1'h0;
  assign \[9]  = f3;
  assign c3 = 1'h0;
  assign e3 = 1'h0;
  assign e4 = 1'h0;
  assign h3 = 1'h0;
  assign j3 = 1'h0;
  assign k3 = 1'h0;
  assign l3 = 1'h0;
  assign m3 = 1'h0;
  assign p3 = 1'h0;
  assign q3 = 1'h0;
  assign r3 = 1'h0;
  assign s3 = 1'h0;
  assign t3 = 1'h0;
  assign u3 = 1'h0;
  assign w3 = 1'h0;
endmodule
