/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "cmlexamples/cc_orig.v:2" *)
(* top =  1  *)
module cc(a, b, c, d, e, f, g, h, i, j, k, l, m, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[0] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[10] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[12] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[13] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[14] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[15] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[16] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[17] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[18] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[19] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[1] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[2] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[3] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[4] ;
  (* src = "cmlexamples/cc_orig.v:46" *)
  wire \[9] ;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input a;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output a0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input b;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output b0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input c;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output c0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input d;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output d0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input e;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output e0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input f;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output f0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input g;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output g0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input h;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output h0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input i;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output i0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input j;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output j0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input k;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output k0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input l;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output l0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input m;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output m0;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output n0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input o;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output o0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input p;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output p0;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input q;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input r;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input s;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input t;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input u;
  (* src = "cmlexamples/cc_orig.v:3" *)
  input v;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output w;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output x;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output y;
  (* src = "cmlexamples/cc_orig.v:25" *)
  output z;
  assign f0 = i & j;
  assign j0 = _02_ & m;
  assign l0 = _03_ & m;
  assign _05_ = _04_ & _15_;
  assign _16_ = i & k;
  assign _00_ = _05_ & _16_;
  assign _17_ = k & i;
  assign _01_ = _06_ & _17_;
  assign m0 = _07_ & m;
  assign o0 = _08_ & m;
  assign _24_ = _09_ & _18_;
  assign _20_ = _10_ & _19_;
  assign n0 = m & _20_;
  assign _25_ = _11_ & _21_;
  assign _23_ = _12_ & _22_;
  assign p0 = m & _23_;
  assign w = v & l;
  assign y = _13_ & m;
  assign i0 = _14_ & m;
  assign _02_ = ~1'h0;
  assign _03_ = ~_00_;
  assign _04_ = ~q;
  assign _15_ = ~d;
  assign _06_ = ~q;
  assign _07_ = ~1'h0;
  assign _08_ = ~1'h0;
  assign _09_ = ~t;
  assign _18_ = ~_01_;
  assign _10_ = ~1'h0;
  assign _19_ = ~_24_;
  assign _11_ = ~v;
  assign _21_ = ~_01_;
  assign _12_ = ~1'h0;
  assign _22_ = ~_25_;
  assign _13_ = ~l;
  assign _14_ = ~1'h0;
  assign a0 = ~t;
  assign g0 = ~f0;
  assign \[0]  = w;
  assign \[10]  = g0;
  assign \[12]  = i0;
  assign \[13]  = j0;
  assign \[14]  = m;
  assign \[15]  = l0;
  assign \[16]  = m0;
  assign \[17]  = n0;
  assign \[18]  = o0;
  assign \[19]  = p0;
  assign \[1]  = 1'h0;
  assign \[2]  = y;
  assign \[3]  = 1'h0;
  assign \[4]  = a0;
  assign \[9]  = f0;
  assign b0 = u;
  assign c0 = q;
  assign d0 = s;
  assign e0 = r;
  assign h0 = p;
  assign k0 = m;
  assign x = 1'h0;
  assign z = 1'h0;
endmodule
