/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/lal_orig.v:2" *)
(* top =  1  *)
module lal(a, b, c, d, e, f, g, h, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[0] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[10] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[11] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[12] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[13] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[14] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[15] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[16] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[17] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[18] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[1] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[3] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[4] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[5] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[6] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[7] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[8] ;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire \[9] ;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input a;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input a0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input b;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output b0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input c;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output c0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input d;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output d0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input e;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output e0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input f;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output f0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input g;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output g0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input h;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output h0;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output i0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input j;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output j0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input k;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output k0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input l;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output l0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input m;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output m0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input n;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output n0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input o;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output o0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input p;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output p0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input q;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output q0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input r;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output r0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input s;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output s0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input t;
  (* src = "LGSynt91/lal_orig.v:30" *)
  output t0;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input u;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input v;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input w;
  (* src = "LGSynt91/lal_orig.v:50" *)
  wire w3;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input x;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input y;
  (* src = "LGSynt91/lal_orig.v:3" *)
  input z;
  assign _058_ = _008_ & g;
  assign e0 = _009_ & _034_;
  assign g0 = _010_ & _035_;
  assign h0 = _011_ & p;
  assign l0 = _012_ & _000_;
  assign _000_ = _013_ & _036_;
  assign _059_ = _014_ & _037_;
  assign _060_ = s & t;
  assign _039_ = _000_ & _038_;
  assign m0 = _015_ & _039_;
  assign _042_ = s & t;
  assign _061_ = _016_ & _040_;
  assign _018_ = _017_ & _041_;
  assign _062_ = u & _042_;
  assign n0 = _018_ & _043_;
  assign _063_ = _019_ & _044_;
  assign _064_ = _020_ & _045_;
  assign _065_ = _021_ & _046_;
  assign _066_ = _022_ & _047_;
  assign _067_ = _023_ & _048_;
  assign b0 = _024_ & j;
  assign _068_ = _025_ & _049_;
  assign _069_ = _026_ & _050_;
  assign _070_ = _027_ & _051_;
  assign _071_ = _028_ & _052_;
  assign _072_ = _029_ & _053_;
  assign _073_ = _030_ & _054_;
  assign _074_ = _031_ & _055_;
  assign _075_ = _032_ & _056_;
  assign _076_ = _033_ & _057_;
  assign _008_ = ~j;
  assign i0 = ~_058_;
  assign _009_ = ~1'h0;
  assign _034_ = ~a0;
  assign _010_ = ~j;
  assign _035_ = ~o;
  assign _011_ = ~j;
  assign _012_ = ~s;
  assign _013_ = ~q;
  assign _036_ = ~h;
  assign _014_ = ~s;
  assign _037_ = ~t;
  assign _038_ = ~_059_;
  assign _015_ = ~_060_;
  assign _017_ = ~_001_;
  assign _016_ = ~u;
  assign _040_ = ~_042_;
  assign _041_ = ~_061_;
  assign _043_ = ~_062_;
  assign _019_ = ~q;
  assign _044_ = ~h;
  assign _001_ = ~_063_;
  assign _020_ = ~_002_;
  assign _045_ = ~h;
  assign o0 = ~_064_;
  assign _021_ = ~1'h0;
  assign _046_ = ~q;
  assign _002_ = ~_065_;
  assign _022_ = ~_003_;
  assign _047_ = ~h;
  assign p0 = ~_066_;
  assign _023_ = ~1'h0;
  assign _048_ = ~q;
  assign _003_ = ~_067_;
  assign _024_ = ~r;
  assign _025_ = ~_004_;
  assign _049_ = ~h;
  assign q0 = ~_068_;
  assign _026_ = ~1'h0;
  assign _050_ = ~q;
  assign _004_ = ~_069_;
  assign _027_ = ~e;
  assign _051_ = ~h;
  assign c0 = ~_070_;
  assign _028_ = ~_005_;
  assign _052_ = ~h;
  assign r0 = ~_071_;
  assign _029_ = ~1'h0;
  assign _053_ = ~q;
  assign _005_ = ~_072_;
  assign _030_ = ~_006_;
  assign _054_ = ~h;
  assign s0 = ~_073_;
  assign _031_ = ~1'h0;
  assign _055_ = ~q;
  assign _006_ = ~_074_;
  assign _032_ = ~_007_;
  assign _056_ = ~h;
  assign t0 = ~_075_;
  assign _033_ = ~1'h0;
  assign _057_ = ~q;
  assign _007_ = ~_076_;
  assign j0 = ~e0;
  assign \[0]  = b0;
  assign \[10]  = l0;
  assign \[11]  = m0;
  assign \[12]  = n0;
  assign \[13]  = o0;
  assign \[14]  = p0;
  assign \[15]  = q0;
  assign \[16]  = r0;
  assign \[17]  = s0;
  assign \[18]  = t0;
  assign \[1]  = c0;
  assign \[3]  = e0;
  assign \[4]  = 1'h0;
  assign \[5]  = g0;
  assign \[6]  = h0;
  assign \[7]  = i0;
  assign \[8]  = j0;
  assign \[9]  = 1'h0;
  assign d0 = r;
  assign f0 = 1'h0;
  assign k0 = 1'h0;
  assign w3 = j0;
endmodule
