/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/cm151a_orig.v:2" *)
(* top =  1  *)
module CM151(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  (* src = "LGSynth91/cm151a_orig.v:19" *)
  wire \[0] ;
  (* src = "LGSynth91/cm151a_orig.v:19" *)
  wire \[1] ;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input a;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input b;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input c;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input d;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input e;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input f;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input g;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input h;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input i;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input j;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input k;
  (* src = "LGSynth91/cm151a_orig.v:3" *)
  input l;
  (* src = "LGSynth91/cm151a_orig.v:16" *)
  output m;
  (* src = "LGSynth91/cm151a_orig.v:16" *)
  output n;
  assign _29_ = _03_ & _14_;
  assign _06_ = _05_ & _15_;
  assign _30_ = _00_ & k;
  assign m = _06_ & _16_;
  assign _31_ = _02_ & _17_;
  assign _32_ = _01_ & j;
  assign _00_ = _07_ & _18_;
  assign _33_ = g & _19_;
  assign _34_ = h & i;
  assign _35_ = _08_ & _20_;
  assign _36_ = e & _21_;
  assign _37_ = f & i;
  assign _38_ = _09_ & _22_;
  assign _39_ = _04_ & j;
  assign _03_ = _10_ & _23_;
  assign _40_ = _11_ & _24_;
  assign _04_ = d & _25_;
  assign _41_ = _03_ & _26_;
  assign _13_ = _12_ & _27_;
  assign _42_ = _00_ & k;
  assign _43_ = _13_ & _28_;
  assign _05_ = ~l;
  assign _14_ = ~k;
  assign _15_ = ~_29_;
  assign _16_ = ~_30_;
  assign _17_ = ~j;
  assign _07_ = ~_31_;
  assign _18_ = ~_32_;
  assign _19_ = ~i;
  assign _08_ = ~_33_;
  assign _20_ = ~_34_;
  assign _01_ = ~_35_;
  assign _21_ = ~i;
  assign _09_ = ~_36_;
  assign _22_ = ~_37_;
  assign _02_ = ~_38_;
  assign _10_ = ~a;
  assign _23_ = ~_39_;
  assign _11_ = ~c;
  assign _24_ = ~i;
  assign _25_ = ~_40_;
  assign _12_ = ~l;
  assign _26_ = ~k;
  assign _27_ = ~_41_;
  assign _28_ = ~_42_;
  assign n = ~_43_;
  assign \[0]  = m;
  assign \[1]  = n;
endmodule
