/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:2" *)
(* top =  1  *)
module count(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[0] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[10] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[11] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[12] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[13] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[14] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[15] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[1] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[2] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[3] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[4] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[5] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[6] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[7] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[8] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:56" *)
  wire \[9] ;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input a;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input a0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input b;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input b0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input c;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input c0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input d;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input d0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input e;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input e0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input f;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input f0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input g;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input g0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input h;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input h0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input i;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input i0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input j;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input j0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input k;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output k0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input l;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output l0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input m;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output m0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input n;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output n0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input o;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output o0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input p;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output p0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input q;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output q0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input r;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output r0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input s;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output s0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output t0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input u;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output u0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input v;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output v0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input w;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output w0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input x;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output x0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input y;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output y0;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:3" *)
  input z;
  (* src = "/LGSynth91/Verilog/cmlexamples/count_orig.v:39" *)
  output z0;
  assign _23_ = _01_ & _12_;
  assign _24_ = _02_ & _13_;
  assign _25_ = _03_ & _14_;
  assign _26_ = _04_ & _15_;
  assign _27_ = _05_ & _16_;
  assign _28_ = _06_ & _17_;
  assign _29_ = _07_ & _18_;
  assign _30_ = _08_ & _19_;
  assign _31_ = _09_ & _20_;
  assign _32_ = _10_ & _21_;
  assign _33_ = _11_ & _22_;
  assign u0 = ~1'h0;
  assign _01_ = ~1'h0;
  assign _12_ = ~s;
  assign w0 = ~_23_;
  assign _02_ = ~f0;
  assign _13_ = ~s;
  assign v0 = ~_24_;
  assign _03_ = ~h0;
  assign _14_ = ~s;
  assign x0 = ~_25_;
  assign _04_ = ~1'h0;
  assign _15_ = ~s;
  assign k0 = ~_26_;
  assign y0 = ~1'h0;
  assign _05_ = ~v;
  assign _16_ = ~s;
  assign l0 = ~_27_;
  assign z0 = ~_00_;
  assign _00_ = ~s;
  assign _06_ = ~w;
  assign _17_ = ~s;
  assign m0 = ~_28_;
  assign _07_ = ~1'h0;
  assign _18_ = ~s;
  assign n0 = ~_29_;
  assign o0 = ~1'h0;
  assign _08_ = ~z;
  assign _19_ = ~s;
  assign p0 = ~_30_;
  assign q0 = ~1'h0;
  assign _09_ = ~b0;
  assign _20_ = ~s;
  assign r0 = ~_31_;
  assign _10_ = ~c0;
  assign _21_ = ~s;
  assign s0 = ~_32_;
  assign _11_ = ~1'h0;
  assign _22_ = ~s;
  assign t0 = ~_33_;
  assign \[0]  = k0;
  assign \[10]  = u0;
  assign \[11]  = v0;
  assign \[12]  = w0;
  assign \[13]  = x0;
  assign \[14]  = y0;
  assign \[15]  = z0;
  assign \[1]  = l0;
  assign \[2]  = m0;
  assign \[3]  = n0;
  assign \[4]  = o0;
  assign \[5]  = p0;
  assign \[6]  = q0;
  assign \[7]  = r0;
  assign \[8]  = s0;
  assign \[9]  = t0;
endmodule
