/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/my_adder_orig.v:2" *)
(* top =  1  *)
module ADDERFDS(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[0] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[10] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[11] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[12] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[13] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[14] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[15] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[16] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[1] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[2] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[3] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[4] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[5] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[6] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[7] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[8] ;
  (* src = "LGSynt91/my_adder_orig.v:55" *)
  wire \[9] ;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input a;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input a0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input b;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input b0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input c;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input c0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input d;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input d0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input e;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input e0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input f;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input f0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input g;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input g0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input h;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output h0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input i;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output i0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input j;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output j0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input k;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output k0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input l;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output l0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input m;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output m0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input n;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output n0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input o;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output o0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input p;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output p0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input q;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output q0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input r;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output r0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input s;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output s0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input t;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output t0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input u;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output u0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input v;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output v0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input w;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output w0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input x;
  (* src = "LGSynt91/my_adder_orig.v:37" *)
  output x0;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input y;
  (* src = "LGSynt91/my_adder_orig.v:3" *)
  input z;
  assign _125_ = _000_ & _060_;
  assign _013_ = _011_ & _061_;
  assign _126_ = _012_ & a0;
  assign _127_ = _013_ & _062_;
  assign _128_ = _014_ & _063_;
  assign _000_ = _001_ & _064_;
  assign _129_ = _015_ & _065_;
  assign _001_ = _002_ & _066_;
  assign _130_ = _016_ & _067_;
  assign _002_ = _003_ & _068_;
  assign _131_ = _017_ & _069_;
  assign _003_ = g0 & _070_;
  assign _132_ = _001_ & _071_;
  assign _020_ = _018_ & _072_;
  assign _133_ = _019_ & b0;
  assign _134_ = _020_ & _073_;
  assign _135_ = _021_ & _074_;
  assign u0 = _022_ & _075_;
  assign _136_ = _003_ & _076_;
  assign _077_ = _023_ & o;
  assign _137_ = e0 & _077_;
  assign _079_ = _024_ & _078_;
  assign _138_ = _025_ & _079_;
  assign v0 = _026_ & _080_;
  assign _139_ = _027_ & _081_;
  assign h0 = _028_ & _082_;
  assign _140_ = _029_ & _083_;
  assign _004_ = _005_ & _084_;
  assign _141_ = _030_ & _085_;
  assign _005_ = _006_ & _086_;
  assign _142_ = _031_ & _087_;
  assign _006_ = _007_ & _088_;
  assign _143_ = _032_ & _089_;
  assign _007_ = _008_ & _090_;
  assign _144_ = _033_ & _091_;
  assign _008_ = _009_ & _092_;
  assign _145_ = _034_ & _093_;
  assign _009_ = _010_ & _094_;
  assign _146_ = _035_ & _095_;
  assign _010_ = _000_ & _096_;
  assign _147_ = g0 & _097_;
  assign _038_ = _036_ & _098_;
  assign _148_ = _037_ & f0;
  assign _149_ = _038_ & _099_;
  assign _150_ = _039_ & _100_;
  assign i0 = _040_ & _101_;
  assign _151_ = _041_ & _102_;
  assign x0 = _004_ & _103_;
  assign _152_ = _042_ & d;
  assign _153_ = t & _104_;
  assign _106_ = _043_ & _105_;
  assign _154_ = _007_ & _106_;
  assign _155_ = _044_ & _107_;
  assign _156_ = _045_ & _108_;
  assign _157_ = _008_ & _109_;
  assign _048_ = _046_ & _110_;
  assign _158_ = _047_ & u;
  assign _159_ = _048_ & _111_;
  assign _160_ = _009_ & _112_;
  assign _113_ = _049_ & f;
  assign _161_ = v & _113_;
  assign _115_ = _050_ & _114_;
  assign _162_ = _051_ & _115_;
  assign m0 = _052_ & _116_;
  assign _163_ = _010_ & _117_;
  assign _118_ = _053_ & h;
  assign _164_ = x & _118_;
  assign _120_ = _054_ & _119_;
  assign _165_ = _055_ & _120_;
  assign o0 = _056_ & _121_;
  assign _166_ = _000_ & _122_;
  assign _059_ = _057_ & _123_;
  assign _167_ = _058_ & y;
  assign _168_ = _059_ & _124_;
  assign _012_ = ~_000_;
  assign _060_ = ~a0;
  assign _011_ = ~k;
  assign _061_ = ~_125_;
  assign _062_ = ~_126_;
  assign r0 = ~_127_;
  assign _014_ = ~b0;
  assign _063_ = ~l;
  assign _064_ = ~_128_;
  assign _015_ = ~c0;
  assign _065_ = ~m;
  assign _066_ = ~_129_;
  assign _016_ = ~d0;
  assign _067_ = ~n;
  assign _068_ = ~_130_;
  assign _017_ = ~f0;
  assign _069_ = ~p;
  assign _070_ = ~_131_;
  assign _019_ = ~_001_;
  assign _071_ = ~b0;
  assign _018_ = ~l;
  assign _072_ = ~_132_;
  assign _073_ = ~_133_;
  assign s0 = ~_134_;
  assign _021_ = ~_003_;
  assign _022_ = ~d0;
  assign _074_ = ~n;
  assign _075_ = ~_135_;
  assign _023_ = ~_003_;
  assign _024_ = ~e0;
  assign _076_ = ~o;
  assign _025_ = ~_136_;
  assign _078_ = ~_077_;
  assign _026_ = ~_137_;
  assign _080_ = ~_138_;
  assign _027_ = ~_004_;
  assign _028_ = ~q;
  assign _081_ = ~a;
  assign _082_ = ~_139_;
  assign _029_ = ~r;
  assign _083_ = ~b;
  assign _084_ = ~_140_;
  assign _030_ = ~s;
  assign _085_ = ~c;
  assign _086_ = ~_141_;
  assign _031_ = ~t;
  assign _087_ = ~d;
  assign _088_ = ~_142_;
  assign _032_ = ~u;
  assign _089_ = ~e;
  assign _090_ = ~_143_;
  assign _033_ = ~v;
  assign _091_ = ~f;
  assign _092_ = ~_144_;
  assign _034_ = ~x;
  assign _093_ = ~h;
  assign _094_ = ~_145_;
  assign _035_ = ~y;
  assign _095_ = ~i;
  assign _096_ = ~_146_;
  assign _037_ = ~g0;
  assign _097_ = ~f0;
  assign _036_ = ~p;
  assign _098_ = ~_147_;
  assign _099_ = ~_148_;
  assign w0 = ~_149_;
  assign _039_ = ~_005_;
  assign _040_ = ~r;
  assign _100_ = ~b;
  assign _101_ = ~_150_;
  assign _041_ = ~q;
  assign _102_ = ~a;
  assign _103_ = ~_151_;
  assign _044_ = ~_007_;
  assign _042_ = ~t;
  assign _104_ = ~d;
  assign _043_ = ~_152_;
  assign _105_ = ~_153_;
  assign _107_ = ~_106_;
  assign _045_ = ~_154_;
  assign _108_ = ~_155_;
  assign k0 = ~_156_;
  assign _047_ = ~_008_;
  assign _109_ = ~u;
  assign _046_ = ~e;
  assign _110_ = ~_157_;
  assign _111_ = ~_158_;
  assign l0 = ~_159_;
  assign _049_ = ~_009_;
  assign _050_ = ~v;
  assign _112_ = ~f;
  assign _051_ = ~_160_;
  assign _114_ = ~_113_;
  assign _052_ = ~_161_;
  assign _116_ = ~_162_;
  assign _053_ = ~_010_;
  assign _054_ = ~x;
  assign _117_ = ~h;
  assign _055_ = ~_163_;
  assign _119_ = ~_118_;
  assign _056_ = ~_164_;
  assign _121_ = ~_165_;
  assign _058_ = ~_000_;
  assign _122_ = ~y;
  assign _057_ = ~i;
  assign _123_ = ~_166_;
  assign _124_ = ~_167_;
  assign p0 = ~_168_;
  assign \[0]  = h0;
  assign \[10]  = r0;
  assign \[11]  = s0;
  assign \[12]  = 1'h0;
  assign \[13]  = u0;
  assign \[14]  = v0;
  assign \[15]  = w0;
  assign \[16]  = x0;
  assign \[1]  = i0;
  assign \[2]  = 1'h0;
  assign \[3]  = k0;
  assign \[4]  = l0;
  assign \[5]  = m0;
  assign \[6]  = 1'h0;
  assign \[7]  = o0;
  assign \[8]  = p0;
  assign \[9]  = 1'h0;
  assign j0 = 1'h0;
  assign n0 = 1'h0;
  assign q0 = 1'h0;
  assign t0 = 1'h0;
endmodule
