/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/f51m_orig.v:2" *)
(* top =  1  *)
module f51m(\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \44 , \45 , \46 , \47 , \48 , \49 , \50 , \51 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \1 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \2 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \3 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \4 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \44 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \45 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \46 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \47 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \48 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \49 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \5 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \50 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \51 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \6 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \7 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \8 ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[1] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[2] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[3] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[4] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[5] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[6] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[7] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[8] ;
  assign _28_ = _08_ & _00_;
  assign _00_ = \8  & _01_;
  assign _29_ = \8  & 1'h0;
  assign _01_ = _02_ & _19_;
  assign _02_ = \7  & _03_;
  assign _03_ = _09_ & _04_;
  assign _04_ = _10_ & 1'h0;
  assign _05_ = _11_ & _06_;
  assign _06_ = _12_ & _07_;
  assign _30_ = _13_ & 1'h0;
  assign _21_ = _14_ & _20_;
  assign _07_ = 1'h0 & _21_;
  assign _23_ = \8  & _22_;
  assign _31_ = _15_ & \7 ;
  assign _32_ = \6  & _23_;
  assign _26_ = _16_ & _24_;
  assign _33_ = _17_ & _25_;
  assign _34_ = \5  & _26_;
  assign _35_ = _18_ & _27_;
  assign \44  = ~1'h0;
  assign _08_ = ~\8 ;
  assign \45  = ~_28_;
  assign _19_ = ~_29_;
  assign _09_ = ~1'h0;
  assign _10_ = ~1'h0;
  assign \46  = ~_05_;
  assign _11_ = ~\8 ;
  assign _12_ = ~1'h0;
  assign _13_ = ~\7 ;
  assign _14_ = ~1'h0;
  assign _20_ = ~_30_;
  assign \47  = ~1'h0;
  assign _15_ = ~\8 ;
  assign _22_ = ~\7 ;
  assign _17_ = ~\5 ;
  assign _16_ = ~_31_;
  assign _24_ = ~_32_;
  assign _25_ = ~_26_;
  assign _18_ = ~_33_;
  assign _27_ = ~_34_;
  assign \48  = ~_35_;
  assign \51  = ~\8 ;
  assign \49  = \6 ;
  assign \50  = 1'h0;
  assign \[1]  = \44 ;
  assign \[2]  = \45 ;
  assign \[3]  = \46 ;
  assign \[4]  = \47 ;
  assign \[5]  = \48 ;
  assign \[6]  = \6 ;
  assign \[7]  = 1'h0;
  assign \[8]  = \51 ;
endmodule
