/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynth91/f51m_orig.v:2" *)
(* top =  1  *)
module f51m(\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \44 , \45 , \46 , \47 , \48 , \49 , \50 , \51 );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \1 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \2 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \3 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \4 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \44 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \45 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \46 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \47 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \48 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \49 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \5 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \50 ;
  (* src = "LGSynth91/f51m_orig.v:12" *)
  output \51 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \6 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \7 ;
  (* src = "LGSynth91/f51m_orig.v:3" *)
  input \8 ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[1] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[2] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[3] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[4] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[5] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[6] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[7] ;
  (* src = "LGSynth91/f51m_orig.v:21" *)
  wire \[8] ;
  assign _063_ = \8  & \7 ;
  assign _064_ = _010_ & _039_;
  assign \50  = _011_ & _040_;
  assign _014_ = _012_ & _041_;
  assign _042_ = _013_ & 1'h0;
  assign _065_ = _014_ & _042_;
  assign _043_ = _015_ & \3 ;
  assign _000_ = _016_ & _043_;
  assign _045_ = _017_ & _044_;
  assign _046_ = _018_ & _045_;
  assign _001_ = _000_ & _046_;
  assign _066_ = _019_ & _002_;
  assign _002_ = \8  & _003_;
  assign _003_ = \7  & _004_;
  assign _004_ = _020_ & _005_;
  assign _022_ = _021_ & 1'h0;
  assign _067_ = 1'h0 & \7 ;
  assign _005_ = _022_ & _047_;
  assign _068_ = _023_ & _009_;
  assign _069_ = _006_ & _048_;
  assign _006_ = _024_ & _007_;
  assign _007_ = _025_ & _008_;
  assign _008_ = _026_ & 1'h0;
  assign _050_ = _027_ & _049_;
  assign _051_ = _028_ & _050_;
  assign _009_ = \5  & _051_;
  assign _031_ = _029_ & _052_;
  assign _053_ = _030_ & 1'h0;
  assign _070_ = _031_ & _053_;
  assign _055_ = \8  & _054_;
  assign _071_ = _032_ & \7 ;
  assign _072_ = \6  & _055_;
  assign _058_ = _033_ & _056_;
  assign _073_ = _034_ & _057_;
  assign _074_ = \5  & _058_;
  assign _075_ = _035_ & _059_;
  assign _060_ = _036_ & \8 ;
  assign _076_ = \6  & _060_;
  assign _077_ = _037_ & _061_;
  assign \49  = _038_ & _062_;
  assign _010_ = ~\8 ;
  assign _039_ = ~\7 ;
  assign _011_ = ~_063_;
  assign _040_ = ~_064_;
  assign _013_ = ~_001_;
  assign _012_ = ~1'h0;
  assign _041_ = ~1'h0;
  assign \44  = ~_065_;
  assign _015_ = ~\2 ;
  assign _016_ = ~\1 ;
  assign _018_ = ~\8 ;
  assign _017_ = ~\6 ;
  assign _044_ = ~\5 ;
  assign _019_ = ~\8 ;
  assign \45  = ~_066_;
  assign _020_ = ~1'h0;
  assign _021_ = ~1'h0;
  assign _047_ = ~_067_;
  assign _023_ = ~\8 ;
  assign _048_ = ~_068_;
  assign \46  = ~_069_;
  assign _024_ = ~\8 ;
  assign _025_ = ~1'h0;
  assign _026_ = ~1'h0;
  assign _028_ = ~\7 ;
  assign _027_ = ~\4 ;
  assign _049_ = ~\3 ;
  assign _030_ = ~1'h0;
  assign _029_ = ~1'h0;
  assign _052_ = ~1'h0;
  assign \47  = ~_070_;
  assign _032_ = ~\8 ;
  assign _054_ = ~\7 ;
  assign _034_ = ~\5 ;
  assign _033_ = ~_071_;
  assign _056_ = ~_072_;
  assign _057_ = ~_058_;
  assign _035_ = ~_073_;
  assign _059_ = ~_074_;
  assign \48  = ~_075_;
  assign _036_ = ~\7 ;
  assign _037_ = ~\6 ;
  assign _061_ = ~_060_;
  assign _038_ = ~_076_;
  assign _062_ = ~_077_;
  assign \51  = ~\8 ;
  assign \[1]  = \44 ;
  assign \[2]  = \45 ;
  assign \[3]  = \46 ;
  assign \[4]  = \47 ;
  assign \[5]  = \48 ;
  assign \[6]  = \49 ;
  assign \[7]  = \50 ;
  assign \[8]  = \51 ;
endmodule
