/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/pm1_orig.v:2" *)
(* top =  1  *)
module pm1(a, b, c, d, e, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[0] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[10] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[11] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[12] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[1] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[2] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[3] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[4] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[5] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[6] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[7] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[8] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[9] ;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input a;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output a0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input b;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output b0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input c;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output c0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input d;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output d0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input e;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input g;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input h;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input i;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input j;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input k;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input l;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input m;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input n;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input o;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input p;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input q;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output r;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output s;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output t;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output u;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output v;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output w;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output x;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output y;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output z;
  assign _06_ = _01_ & _05_;
  assign _08_ = _02_ & _06_;
  assign _09_ = _03_ & n;
  assign _07_ = k & m;
  assign _10_ = _04_ & _07_;
  assign _01_ = ~n;
  assign _02_ = ~m;
  assign _05_ = ~b;
  assign r = ~_08_;
  assign _03_ = ~m;
  assign s = ~_09_;
  assign t = ~1'h0;
  assign _04_ = ~_00_;
  assign u = ~_10_;
  assign _00_ = ~n;
  assign z = ~1'h0;
  assign v = ~p;
  assign w = ~o;
  assign y = ~q;
  assign \[0]  = r;
  assign \[10]  = 1'h0;
  assign \[11]  = 1'h0;
  assign \[12]  = 1'h0;
  assign \[1]  = s;
  assign \[2]  = t;
  assign \[3]  = u;
  assign \[4]  = v;
  assign \[5]  = w;
  assign \[6]  = 1'h0;
  assign \[7]  = y;
  assign \[8]  = z;
  assign \[9]  = 1'h0;
  assign a0 = 1'h0;
  assign b0 = 1'h0;
  assign c0 = 1'h0;
  assign d0 = 1'h0;
  assign x = 1'h0;
endmodule
