/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/pm1_orig.v:2" *)
(* top =  1  *)
module pm1(a, b, c, d, e, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[0] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[10] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[11] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[12] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[1] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[2] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[3] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[4] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[5] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[6] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[7] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[8] ;
  (* src = "LGSynt91/pm1_orig.v:34" *)
  wire \[9] ;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input a;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output a0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input b;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output b0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input c;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output c0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input d;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output d0;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input e;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input g;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input h;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input i;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input j;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input k;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input l;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input m;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input n;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input o;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input p;
  (* src = "LGSynt91/pm1_orig.v:3" *)
  input q;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output r;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output s;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output t;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output u;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output v;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output w;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output x;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output y;
  (* src = "LGSynt91/pm1_orig.v:20" *)
  output z;
  assign _23_ = _07_ & _22_;
  assign _34_ = _08_ & _23_;
  assign _35_ = _09_ & n;
  assign _00_ = n & m;
  assign _24_ = k & m;
  assign _36_ = _10_ & _24_;
  assign _25_ = s & c;
  assign _37_ = _03_ & _25_;
  assign x = _02_ & _26_;
  assign _02_ = k & b;
  assign _03_ = d & e;
  assign _27_ = _11_ & a;
  assign _38_ = _12_ & _27_;
  assign _28_ = _13_ & _00_;
  assign b0 = _14_ & _28_;
  assign _39_ = a & k;
  assign _16_ = _15_ & a;
  assign _40_ = m & _29_;
  assign _18_ = _16_ & _30_;
  assign _41_ = _17_ & n;
  assign a0 = _18_ & _31_;
  assign c0 = m & _06_;
  assign _06_ = _19_ & a;
  assign _21_ = _20_ & _32_;
  assign _33_ = a & _00_;
  assign d0 = _21_ & _33_;
  assign _07_ = ~n;
  assign _08_ = ~m;
  assign _22_ = ~b;
  assign r = ~_34_;
  assign _09_ = ~m;
  assign s = ~_35_;
  assign t = ~1'h0;
  assign _10_ = ~_01_;
  assign u = ~_36_;
  assign _01_ = ~n;
  assign _26_ = ~_37_;
  assign _11_ = ~_04_;
  assign _12_ = ~l;
  assign z = ~_38_;
  assign _04_ = ~m;
  assign _13_ = ~_05_;
  assign _14_ = ~l;
  assign _05_ = ~_39_;
  assign _15_ = ~l;
  assign _17_ = ~m;
  assign _29_ = ~n;
  assign _30_ = ~_40_;
  assign _31_ = ~_41_;
  assign _19_ = ~l;
  assign _20_ = ~k;
  assign _32_ = ~l;
  assign v = ~p;
  assign w = ~o;
  assign y = ~q;
  assign \[0]  = r;
  assign \[10]  = b0;
  assign \[11]  = c0;
  assign \[12]  = d0;
  assign \[1]  = s;
  assign \[2]  = t;
  assign \[3]  = u;
  assign \[4]  = v;
  assign \[5]  = w;
  assign \[6]  = x;
  assign \[7]  = y;
  assign \[8]  = z;
  assign \[9]  = a0;
endmodule
