/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/c8_orig.v:2" *)
(* top =  1  *)
module c8(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[0] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[10] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[11] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[12] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[13] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[14] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[15] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[16] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[17] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[1] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[2] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[3] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[4] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[5] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[6] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[7] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[9] ;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input a;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input a0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input b;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input b0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input c;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input c0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input d;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output d0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input e;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output e0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input f;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output f0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input g;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output g0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input h;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output h0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input i;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output i0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input j;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output j0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input k;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output k0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input l;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output l0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input m;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output m0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input n;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output n0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input o;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output o0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input p;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output p0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input q;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output q0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input r;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output r0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input s;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output s0;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output t0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input u;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output u0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input v;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input w;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input x;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input y;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input z;
  assign _103_ = i & c0;
  assign _104_ = u & _059_;
  assign d0 = _018_ & _060_;
  assign _021_ = _019_ & _061_;
  assign _062_ = _020_ & _000_;
  assign _105_ = _021_ & _062_;
  assign _063_ = _016_ & 1'h0;
  assign _015_ = _022_ & _063_;
  assign _106_ = o & _064_;
  assign _024_ = _023_ & _065_;
  assign _107_ = g & s;
  assign _108_ = _024_ & _066_;
  assign _068_ = _025_ & _067_;
  assign _069_ = _026_ & _068_;
  assign _017_ = a0 & _069_;
  assign _000_ = _027_ & _001_;
  assign _109_ = _028_ & _016_;
  assign _110_ = j & c0;
  assign _111_ = v & _070_;
  assign e0 = _029_ & _071_;
  assign _032_ = _030_ & _072_;
  assign _073_ = _031_ & _002_;
  assign _112_ = _032_ & _073_;
  assign _113_ = _033_ & _003_;
  assign _114_ = h & s;
  assign _075_ = _034_ & _074_;
  assign _115_ = _035_ & _075_;
  assign _116_ = k & c0;
  assign _117_ = w & _076_;
  assign f0 = _036_ & _077_;
  assign _118_ = x & _078_;
  assign g0 = _037_ & _079_;
  assign _119_ = y & _080_;
  assign _120_ = m & c0;
  assign h0 = _038_ & _081_;
  assign _121_ = z & _082_;
  assign _122_ = n & c0;
  assign i0 = _039_ & _083_;
  assign _123_ = a0 & _084_;
  assign _124_ = o & c0;
  assign j0 = _040_ & _085_;
  assign _125_ = b0 & _086_;
  assign _126_ = p & c0;
  assign k0 = _041_ & _087_;
  assign _088_ = _042_ & q;
  assign _127_ = _043_ & _088_;
  assign n0 = 1'h0 & _089_;
  assign _004_ = _044_ & _090_;
  assign _047_ = _045_ & _091_;
  assign _092_ = _046_ & _005_;
  assign _128_ = _047_ & _092_;
  assign _129_ = _048_ & _006_;
  assign _130_ = k & _093_;
  assign _050_ = _049_ & _094_;
  assign _131_ = c & s;
  assign _132_ = _050_ & _095_;
  assign _007_ = _006_ & 1'h0;
  assign _133_ = _051_ & _096_;
  assign _134_ = _011_ & _097_;
  assign _135_ = _008_ & _098_;
  assign _008_ = _052_ & _009_;
  assign _099_ = _011_ & r;
  assign _136_ = x & _099_;
  assign _009_ = _010_ & _100_;
  assign _137_ = _053_ & _011_;
  assign _138_ = _054_ & _101_;
  assign _139_ = _055_ & _012_;
  assign _012_ = _056_ & _013_;
  assign _140_ = _057_ & _014_;
  assign _141_ = _058_ & _102_;
  assign _059_ = ~c0;
  assign _018_ = ~_103_;
  assign _060_ = ~_104_;
  assign _020_ = ~_015_;
  assign _019_ = ~1'h0;
  assign _061_ = ~1'h0;
  assign s0 = ~_105_;
  assign _022_ = ~_017_;
  assign _023_ = ~q;
  assign _064_ = ~s;
  assign _065_ = ~_106_;
  assign _066_ = ~_107_;
  assign _016_ = ~_108_;
  assign _026_ = ~x;
  assign _025_ = ~y;
  assign _067_ = ~z;
  assign _027_ = ~_016_;
  assign _028_ = ~q;
  assign _001_ = ~_109_;
  assign _070_ = ~c0;
  assign _029_ = ~_110_;
  assign _071_ = ~_111_;
  assign _031_ = ~1'h0;
  assign _030_ = ~1'h0;
  assign _072_ = ~1'h0;
  assign t0 = ~_112_;
  assign _033_ = ~q;
  assign _002_ = ~_113_;
  assign _034_ = ~p;
  assign _035_ = ~q;
  assign _074_ = ~_114_;
  assign _003_ = ~_115_;
  assign _076_ = ~c0;
  assign _036_ = ~_116_;
  assign _077_ = ~_117_;
  assign _037_ = ~l;
  assign _078_ = ~c0;
  assign _079_ = ~_118_;
  assign _080_ = ~c0;
  assign _038_ = ~_119_;
  assign _081_ = ~_120_;
  assign _082_ = ~c0;
  assign _039_ = ~_121_;
  assign _083_ = ~_122_;
  assign _084_ = ~c0;
  assign _040_ = ~_123_;
  assign _085_ = ~_124_;
  assign _086_ = ~c0;
  assign _041_ = ~_125_;
  assign _087_ = ~_126_;
  assign m0 = ~1'h0;
  assign _042_ = ~_004_;
  assign _043_ = ~v;
  assign _089_ = ~_127_;
  assign _044_ = ~u;
  assign _090_ = ~r;
  assign _046_ = ~_007_;
  assign _045_ = ~1'h0;
  assign _091_ = ~1'h0;
  assign o0 = ~_128_;
  assign _048_ = ~q;
  assign _005_ = ~_129_;
  assign _049_ = ~q;
  assign _093_ = ~s;
  assign _094_ = ~_130_;
  assign _095_ = ~_131_;
  assign _006_ = ~_132_;
  assign _051_ = ~1'h0;
  assign _096_ = ~1'h0;
  assign _097_ = ~_133_;
  assign _098_ = ~_134_;
  assign p0 = ~_135_;
  assign _052_ = ~_011_;
  assign _100_ = ~_136_;
  assign _053_ = ~q;
  assign _010_ = ~_137_;
  assign _054_ = ~l;
  assign _101_ = ~q;
  assign _011_ = ~_138_;
  assign _055_ = ~_014_;
  assign q0 = ~_139_;
  assign _056_ = ~_014_;
  assign _057_ = ~q;
  assign _013_ = ~_140_;
  assign _058_ = ~m;
  assign _102_ = ~q;
  assign _014_ = ~_141_;
  assign r0 = ~1'h0;
  assign \[0]  = d0;
  assign \[10]  = n0;
  assign \[11]  = o0;
  assign \[12]  = p0;
  assign \[13]  = q0;
  assign \[14]  = r0;
  assign \[15]  = s0;
  assign \[16]  = t0;
  assign \[17]  = 1'h0;
  assign \[1]  = e0;
  assign \[2]  = f0;
  assign \[3]  = g0;
  assign \[4]  = h0;
  assign \[5]  = i0;
  assign \[6]  = j0;
  assign \[7]  = k0;
  assign \[9]  = m0;
  assign l0 = c0;
  assign u0 = 1'h0;
endmodule
