/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/c8_orig.v:2" *)
(* top =  1  *)
module c8(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[0] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[10] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[11] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[12] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[13] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[14] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[15] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[16] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[17] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[1] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[2] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[3] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[4] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[5] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[6] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[7] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[9] ;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input a;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input a0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input b;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input b0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input c;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input c0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input d;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output d0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input e;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output e0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input f;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output f0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input g;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output g0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input h;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output h0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input i;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output i0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input j;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output j0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input k;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output k0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input l;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output l0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input m;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output m0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input n;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output n0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input o;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output o0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input p;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output p0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input q;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output q0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input r;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output r0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input s;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output s0;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output t0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input u;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output u0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input v;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input w;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input x;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input y;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input z;
  assign _098_ = g & s;
  assign _060_ = _017_ & _059_;
  assign _099_ = _018_ & _060_;
  assign _062_ = _019_ & _061_;
  assign _063_ = _020_ & _062_;
  assign _016_ = a0 & _063_;
  assign _000_ = _021_ & _001_;
  assign _100_ = _022_ & _015_;
  assign _101_ = j & c0;
  assign _102_ = v & _064_;
  assign e0 = _023_ & _065_;
  assign _103_ = k & c0;
  assign _104_ = w & _066_;
  assign f0 = _024_ & _067_;
  assign _105_ = l & c0;
  assign _106_ = x & _068_;
  assign g0 = _025_ & _069_;
  assign _107_ = y & _070_;
  assign _108_ = m & c0;
  assign h0 = _026_ & _071_;
  assign _109_ = z & _072_;
  assign _110_ = n & c0;
  assign i0 = _027_ & _073_;
  assign _111_ = a0 & _074_;
  assign _112_ = o & c0;
  assign j0 = _028_ & _075_;
  assign _113_ = b0 & _076_;
  assign _114_ = p & c0;
  assign k0 = _029_ & _077_;
  assign _032_ = _030_ & _078_;
  assign _079_ = _031_ & 1'h0;
  assign _115_ = _032_ & _079_;
  assign _034_ = _033_ & _080_;
  assign _081_ = s & a;
  assign _002_ = _034_ & _081_;
  assign _036_ = _035_ & _082_;
  assign _083_ = i & a;
  assign _003_ = _036_ & _083_;
  assign _084_ = _037_ & q;
  assign _116_ = _038_ & _084_;
  assign n0 = 1'h0 & _085_;
  assign _004_ = _039_ & _086_;
  assign _042_ = _040_ & _087_;
  assign _088_ = _041_ & _005_;
  assign _117_ = _042_ & _088_;
  assign _118_ = _043_ & _006_;
  assign _119_ = c & s;
  assign _090_ = _044_ & _089_;
  assign _120_ = _045_ & _090_;
  assign _007_ = _006_ & 1'h0;
  assign _121_ = _046_ & _008_;
  assign _008_ = _047_ & _009_;
  assign _122_ = _048_ & _010_;
  assign _123_ = _049_ & _091_;
  assign _124_ = _050_ & _011_;
  assign _011_ = _051_ & _012_;
  assign _125_ = _052_ & _013_;
  assign _126_ = _053_ & _092_;
  assign _127_ = i & c0;
  assign _128_ = u & _093_;
  assign d0 = _054_ & _094_;
  assign _057_ = _055_ & _095_;
  assign _096_ = _056_ & _000_;
  assign _129_ = _057_ & _096_;
  assign _097_ = _015_ & 1'h0;
  assign _014_ = _058_ & _097_;
  assign _017_ = ~o;
  assign _018_ = ~q;
  assign _059_ = ~_098_;
  assign _015_ = ~_099_;
  assign _020_ = ~x;
  assign _019_ = ~y;
  assign _061_ = ~z;
  assign _021_ = ~_015_;
  assign _022_ = ~q;
  assign _001_ = ~_100_;
  assign _064_ = ~c0;
  assign _023_ = ~_101_;
  assign _065_ = ~_102_;
  assign t0 = ~1'h0;
  assign _066_ = ~c0;
  assign _024_ = ~_103_;
  assign _067_ = ~_104_;
  assign _068_ = ~c0;
  assign _025_ = ~_105_;
  assign _069_ = ~_106_;
  assign _070_ = ~c0;
  assign _026_ = ~_107_;
  assign _071_ = ~_108_;
  assign _072_ = ~c0;
  assign _027_ = ~_109_;
  assign _073_ = ~_110_;
  assign _074_ = ~c0;
  assign _028_ = ~_111_;
  assign _075_ = ~_112_;
  assign _076_ = ~c0;
  assign _029_ = ~_113_;
  assign _077_ = ~_114_;
  assign _031_ = ~_002_;
  assign _030_ = ~_003_;
  assign _078_ = ~1'h0;
  assign m0 = ~_115_;
  assign _033_ = ~u;
  assign _080_ = ~r;
  assign _035_ = ~u;
  assign _082_ = ~r;
  assign _037_ = ~_004_;
  assign _038_ = ~v;
  assign _085_ = ~_116_;
  assign _039_ = ~u;
  assign _086_ = ~r;
  assign _041_ = ~_007_;
  assign _040_ = ~1'h0;
  assign _087_ = ~1'h0;
  assign o0 = ~_117_;
  assign _043_ = ~q;
  assign _005_ = ~_118_;
  assign _044_ = ~k;
  assign _045_ = ~q;
  assign _089_ = ~_119_;
  assign _006_ = ~_120_;
  assign _046_ = ~_010_;
  assign p0 = ~_121_;
  assign _047_ = ~_010_;
  assign _048_ = ~q;
  assign _009_ = ~_122_;
  assign _049_ = ~l;
  assign _091_ = ~q;
  assign _010_ = ~_123_;
  assign _050_ = ~_013_;
  assign q0 = ~_124_;
  assign _051_ = ~_013_;
  assign _052_ = ~q;
  assign _012_ = ~_125_;
  assign _053_ = ~m;
  assign _092_ = ~q;
  assign _013_ = ~_126_;
  assign r0 = ~1'h0;
  assign _093_ = ~c0;
  assign _054_ = ~_127_;
  assign _094_ = ~_128_;
  assign _056_ = ~_014_;
  assign _055_ = ~1'h0;
  assign _095_ = ~1'h0;
  assign s0 = ~_129_;
  assign _058_ = ~_016_;
  assign \[0]  = d0;
  assign \[10]  = n0;
  assign \[11]  = o0;
  assign \[12]  = p0;
  assign \[13]  = q0;
  assign \[14]  = r0;
  assign \[15]  = s0;
  assign \[16]  = t0;
  assign \[17]  = 1'h0;
  assign \[1]  = e0;
  assign \[2]  = f0;
  assign \[3]  = g0;
  assign \[4]  = h0;
  assign \[5]  = i0;
  assign \[6]  = j0;
  assign \[7]  = k0;
  assign \[9]  = m0;
  assign l0 = c0;
  assign u0 = 1'h0;
endmodule
