/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/c8_orig.v:2" *)
(* top =  1  *)
module c8(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[0] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[10] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[11] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[12] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[13] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[14] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[15] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[16] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[17] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[1] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[2] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[3] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[4] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[5] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[6] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[7] ;
  (* src = "LGSynt91/c8_orig.v:51" *)
  wire \[9] ;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input a;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input a0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input b;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input b0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input c;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input c0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input d;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output d0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input e;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output e0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input f;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output f0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input g;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output g0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input h;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output h0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input i;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output i0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input j;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output j0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input k;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output k0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input l;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output l0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input m;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output m0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input n;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output n0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input o;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output o0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input p;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output p0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input q;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output q0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input r;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output r0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input s;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output s0;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output t0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input u;
  (* src = "LGSynt91/c8_orig.v:32" *)
  output u0;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input v;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input w;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input x;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input y;
  (* src = "LGSynt91/c8_orig.v:3" *)
  input z;
  assign _063_ = u & _036_;
  assign d0 = _011_ & _037_;
  assign _064_ = v & _038_;
  assign e0 = _012_ & _039_;
  assign _065_ = w & _040_;
  assign f0 = _013_ & _041_;
  assign _066_ = l & c0;
  assign _067_ = x & _042_;
  assign g0 = _014_ & _043_;
  assign _068_ = y & _044_;
  assign _069_ = m & c0;
  assign h0 = _015_ & _045_;
  assign _070_ = z & _046_;
  assign _071_ = n & c0;
  assign i0 = _016_ & _047_;
  assign _072_ = a0 & _048_;
  assign _073_ = o & c0;
  assign j0 = _017_ & _049_;
  assign _074_ = b0 & _050_;
  assign _075_ = p & c0;
  assign k0 = _018_ & _051_;
  assign _052_ = _019_ & q;
  assign _076_ = _020_ & _052_;
  assign n0 = 1'h0 & _053_;
  assign _000_ = _021_ & _054_;
  assign _024_ = _022_ & _055_;
  assign _056_ = _023_ & _001_;
  assign _077_ = _024_ & _056_;
  assign _057_ = _003_ & v;
  assign _078_ = w & _057_;
  assign _001_ = _002_ & _058_;
  assign _079_ = _025_ & _003_;
  assign _080_ = _026_ & _059_;
  assign _004_ = _003_ & 1'h0;
  assign _081_ = _027_ & _005_;
  assign _005_ = _028_ & _006_;
  assign _082_ = _029_ & _007_;
  assign _083_ = _030_ & _060_;
  assign _084_ = _031_ & _008_;
  assign _008_ = _032_ & _009_;
  assign _085_ = _033_ & _010_;
  assign _086_ = e & s;
  assign _062_ = _034_ & _061_;
  assign _087_ = _035_ & _062_;
  assign _011_ = ~i;
  assign _036_ = ~c0;
  assign _037_ = ~_063_;
  assign s0 = ~1'h0;
  assign _012_ = ~j;
  assign _038_ = ~c0;
  assign _039_ = ~_064_;
  assign t0 = ~1'h0;
  assign _013_ = ~k;
  assign _040_ = ~c0;
  assign _041_ = ~_065_;
  assign _042_ = ~c0;
  assign _014_ = ~_066_;
  assign _043_ = ~_067_;
  assign _044_ = ~c0;
  assign _015_ = ~_068_;
  assign _045_ = ~_069_;
  assign _046_ = ~c0;
  assign _016_ = ~_070_;
  assign _047_ = ~_071_;
  assign _048_ = ~c0;
  assign _017_ = ~_072_;
  assign _049_ = ~_073_;
  assign _050_ = ~c0;
  assign _018_ = ~_074_;
  assign _051_ = ~_075_;
  assign m0 = ~1'h0;
  assign _019_ = ~_000_;
  assign _020_ = ~v;
  assign _053_ = ~_076_;
  assign _021_ = ~u;
  assign _054_ = ~r;
  assign _023_ = ~_004_;
  assign _022_ = ~1'h0;
  assign _055_ = ~1'h0;
  assign o0 = ~_077_;
  assign _058_ = ~_078_;
  assign _025_ = ~q;
  assign _002_ = ~_079_;
  assign _026_ = ~k;
  assign _059_ = ~q;
  assign _003_ = ~_080_;
  assign _027_ = ~_007_;
  assign p0 = ~_081_;
  assign _028_ = ~_007_;
  assign _029_ = ~q;
  assign _006_ = ~_082_;
  assign _030_ = ~l;
  assign _060_ = ~q;
  assign _007_ = ~_083_;
  assign _031_ = ~_010_;
  assign q0 = ~_084_;
  assign _032_ = ~_010_;
  assign _033_ = ~q;
  assign _009_ = ~_085_;
  assign _034_ = ~m;
  assign _035_ = ~q;
  assign _061_ = ~_086_;
  assign _010_ = ~_087_;
  assign r0 = ~1'h0;
  assign \[0]  = d0;
  assign \[10]  = n0;
  assign \[11]  = o0;
  assign \[12]  = p0;
  assign \[13]  = q0;
  assign \[14]  = r0;
  assign \[15]  = s0;
  assign \[16]  = t0;
  assign \[17]  = 1'h0;
  assign \[1]  = e0;
  assign \[2]  = f0;
  assign \[3]  = g0;
  assign \[4]  = h0;
  assign \[5]  = i0;
  assign \[6]  = j0;
  assign \[7]  = k0;
  assign \[9]  = m0;
  assign l0 = c0;
  assign u0 = 1'h0;
endmodule
