/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/vda_orig.v:2" *)
(* top =  1  *)
module vda(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, a1, b1, c1, d1);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[0] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[10] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[11] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[12] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[13] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[14] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[15] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[16] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[17] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[18] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[19] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[1] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[20] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[21] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[22] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[23] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[24] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[25] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[26] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[27] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[28] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[29] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[2] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[30] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[31] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[32] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[33] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[34] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[35] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[36] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[37] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[38] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[3] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[4] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[5] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[6] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[7] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[8] ;
  (* src = "LGSynt91/vda_orig.v:61" *)
  wire \[9] ;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input a;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output a0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output a1;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input b;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output b0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output b1;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input c;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output c0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output c1;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input d;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output d0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output d1;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input e;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output e0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input f;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output f0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input g;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output g0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input h;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output h0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input i;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output i0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input j;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output j0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input k;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output k0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input l;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output l0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input m;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output m0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input n;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output n0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input o;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output o0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input p;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output p0;
  (* src = "LGSynt91/vda_orig.v:3" *)
  input q;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output q0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output r;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output r0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output s;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output s0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output t;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output t0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output u;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output u0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output v;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output v0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output w;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output w0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output x;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output x0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output y;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output y0;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output z;
  (* src = "LGSynt91/vda_orig.v:21" *)
  output z0;
  assign _118_ = _029_ & p;
  assign a1 = q & _118_;
  assign _120_ = _030_ & _119_;
  assign _121_ = _031_ & _120_;
  assign _029_ = l & _121_;
  assign _122_ = l & m;
  assign _000_ = _032_ & _122_;
  assign _123_ = _033_ & _002_;
  assign _001_ = _034_ & _123_;
  assign _035_ = l & m;
  assign _124_ = o & n;
  assign _002_ = _035_ & _124_;
  assign _125_ = p & 1'h0;
  assign _126_ = o & _125_;
  assign _003_ = _036_ & _126_;
  assign _004_ = _037_ & _005_;
  assign _127_ = p & 1'h0;
  assign _128_ = o & _127_;
  assign _005_ = _038_ & _128_;
  assign _129_ = _039_ & _029_;
  assign _006_ = _040_ & _129_;
  assign _130_ = _000_ & q;
  assign _131_ = o & _130_;
  assign _007_ = _041_ & _131_;
  assign _132_ = _042_ & 1'h0;
  assign _008_ = _043_ & _132_;
  assign _133_ = p & _010_;
  assign _009_ = _044_ & _133_;
  assign _046_ = _045_ & _134_;
  assign _135_ = l & o;
  assign _010_ = _046_ & _135_;
  assign _136_ = p & q;
  assign _137_ = _012_ & _136_;
  assign _011_ = _047_ & _137_;
  assign _049_ = _048_ & _138_;
  assign _139_ = n & i;
  assign _012_ = _049_ & _139_;
  assign _051_ = _050_ & _140_;
  assign _141_ = o & _000_;
  assign _013_ = _051_ & _141_;
  assign _142_ = 1'h0 & q;
  assign d1 = _052_ & _142_;
  assign _054_ = _053_ & _143_;
  assign _144_ = 1'h0 & q;
  assign c0 = _054_ & _144_;
  assign _201_ = _055_ & _014_;
  assign _146_ = _056_ & _145_;
  assign _147_ = _057_ & _146_;
  assign _014_ = 1'h0 & _147_;
  assign _148_ = 1'h0 & p;
  assign _015_ = q & _148_;
  assign _149_ = _058_ & _018_;
  assign _202_ = _059_ & _149_;
  assign _203_ = _016_ & _150_;
  assign _152_ = _060_ & _151_;
  assign _153_ = _061_ & _152_;
  assign _016_ = 1'h0 & _153_;
  assign _154_ = _062_ & 1'h0;
  assign _017_ = _063_ & _154_;
  assign _066_ = _064_ & _155_;
  assign _157_ = _065_ & _156_;
  assign _018_ = _066_ & _157_;
  assign _158_ = _067_ & 1'h0;
  assign _204_ = _068_ & _158_;
  assign _159_ = _069_ & _019_;
  assign _205_ = _070_ & _159_;
  assign _161_ = _071_ & _160_;
  assign _162_ = _072_ & _161_;
  assign _019_ = _020_ & _162_;
  assign _164_ = _073_ & _163_;
  assign _165_ = _074_ & _164_;
  assign _020_ = _021_ & _165_;
  assign _167_ = _075_ & _166_;
  assign _168_ = _076_ & _167_;
  assign _021_ = 1'h0 & _168_;
  assign _169_ = _077_ & 1'h0;
  assign _206_ = _078_ & _169_;
  assign _170_ = _079_ & _022_;
  assign _207_ = _080_ & _170_;
  assign _083_ = _081_ & _171_;
  assign _173_ = _082_ & _172_;
  assign _022_ = _083_ & _173_;
  assign _174_ = 1'h0 & q;
  assign _023_ = _084_ & _174_;
  assign _085_ = 1'h0 & q;
  assign _175_ = p & o;
  assign _024_ = _085_ & _175_;
  assign _208_ = _086_ & 1'h0;
  assign _176_ = _087_ & 1'h0;
  assign _209_ = _088_ & _176_;
  assign _210_ = _089_ & _177_;
  assign _178_ = _090_ & 1'h0;
  assign _211_ = _091_ & _178_;
  assign _094_ = _092_ & _179_;
  assign _181_ = _093_ & _180_;
  assign _212_ = _094_ & _181_;
  assign _182_ = _095_ & 1'h0;
  assign _213_ = _096_ & _182_;
  assign _183_ = _097_ & _025_;
  assign _214_ = _098_ & _183_;
  assign _185_ = _099_ & _184_;
  assign _186_ = _100_ & _185_;
  assign _025_ = _026_ & _186_;
  assign _188_ = _101_ & _187_;
  assign _189_ = _102_ & _188_;
  assign _026_ = _027_ & _189_;
  assign _190_ = _103_ & 1'h0;
  assign _027_ = _104_ & _190_;
  assign _107_ = _105_ & _191_;
  assign _192_ = _106_ & 1'h0;
  assign _215_ = _107_ & _192_;
  assign _216_ = _108_ & _193_;
  assign _217_ = _109_ & _028_;
  assign _195_ = _110_ & _194_;
  assign _196_ = _111_ & _195_;
  assign _028_ = 1'h0 & _196_;
  assign _114_ = _112_ & _197_;
  assign _198_ = _113_ & 1'h0;
  assign _218_ = _114_ & _198_;
  assign _117_ = _115_ & _199_;
  assign _200_ = _116_ & 1'h0;
  assign _219_ = _117_ & _200_;
  assign _031_ = ~o;
  assign _030_ = ~n;
  assign _119_ = ~m;
  assign g0 = ~1'h0;
  assign _032_ = ~n;
  assign _033_ = ~p;
  assign _034_ = ~q;
  assign _036_ = ~q;
  assign _037_ = ~q;
  assign _038_ = ~n;
  assign _039_ = ~p;
  assign _040_ = ~q;
  assign _041_ = ~p;
  assign _042_ = ~p;
  assign _043_ = ~q;
  assign _044_ = ~q;
  assign _045_ = ~n;
  assign _134_ = ~m;
  assign _047_ = ~o;
  assign _048_ = ~l;
  assign _138_ = ~m;
  assign _050_ = ~p;
  assign _140_ = ~q;
  assign _052_ = ~p;
  assign _053_ = ~p;
  assign _143_ = ~o;
  assign _055_ = ~_013_;
  assign h0 = ~_201_;
  assign _057_ = ~1'h0;
  assign _056_ = ~1'h0;
  assign _145_ = ~1'h0;
  assign _058_ = ~p;
  assign _059_ = ~o;
  assign _150_ = ~_202_;
  assign i0 = ~_203_;
  assign _061_ = ~1'h0;
  assign _060_ = ~_013_;
  assign _151_ = ~1'h0;
  assign _062_ = ~p;
  assign _063_ = ~q;
  assign _065_ = ~l;
  assign _064_ = ~c;
  assign _155_ = ~n;
  assign _156_ = ~m;
  assign _067_ = ~_003_;
  assign _068_ = ~_001_;
  assign j0 = ~_204_;
  assign k0 = ~1'h0;
  assign _069_ = ~1'h0;
  assign _070_ = ~_013_;
  assign r = ~_205_;
  assign _072_ = ~1'h0;
  assign _071_ = ~1'h0;
  assign _160_ = ~1'h0;
  assign _074_ = ~1'h0;
  assign _073_ = ~1'h0;
  assign _163_ = ~1'h0;
  assign _076_ = ~_009_;
  assign _075_ = ~_017_;
  assign _166_ = ~1'h0;
  assign s = ~1'h0;
  assign l0 = ~1'h0;
  assign t = ~1'h0;
  assign _077_ = ~1'h0;
  assign _078_ = ~_013_;
  assign m0 = ~_206_;
  assign _079_ = ~_007_;
  assign _080_ = ~1'h0;
  assign u = ~_207_;
  assign _082_ = ~c0;
  assign _081_ = ~1'h0;
  assign _171_ = ~_023_;
  assign _172_ = ~_024_;
  assign _084_ = ~p;
  assign n0 = ~1'h0;
  assign _086_ = ~1'h0;
  assign v = ~_208_;
  assign o0 = ~1'h0;
  assign p0 = ~1'h0;
  assign q0 = ~1'h0;
  assign y = ~1'h0;
  assign _087_ = ~1'h0;
  assign _088_ = ~_013_;
  assign r0 = ~_209_;
  assign _089_ = ~_008_;
  assign _177_ = ~1'h0;
  assign z = ~_210_;
  assign _090_ = ~1'h0;
  assign _091_ = ~_013_;
  assign s0 = ~_211_;
  assign _093_ = ~c0;
  assign _092_ = ~1'h0;
  assign _179_ = ~1'h0;
  assign _180_ = ~1'h0;
  assign a0 = ~_212_;
  assign _095_ = ~1'h0;
  assign _096_ = ~1'h0;
  assign t0 = ~_213_;
  assign u0 = ~1'h0;
  assign v0 = ~1'h0;
  assign w0 = ~1'h0;
  assign _097_ = ~1'h0;
  assign _098_ = ~_013_;
  assign x0 = ~_214_;
  assign _100_ = ~1'h0;
  assign _099_ = ~_011_;
  assign _184_ = ~1'h0;
  assign _102_ = ~1'h0;
  assign _101_ = ~_023_;
  assign _187_ = ~_024_;
  assign _103_ = ~_004_;
  assign _104_ = ~1'h0;
  assign _106_ = ~1'h0;
  assign _105_ = ~_013_;
  assign _191_ = ~1'h0;
  assign y0 = ~_215_;
  assign _108_ = ~_006_;
  assign _193_ = ~_015_;
  assign c1 = ~_216_;
  assign _109_ = ~_013_;
  assign d0 = ~_217_;
  assign _111_ = ~1'h0;
  assign _110_ = ~1'h0;
  assign _194_ = ~1'h0;
  assign _113_ = ~1'h0;
  assign _112_ = ~1'h0;
  assign _197_ = ~1'h0;
  assign e0 = ~_218_;
  assign _116_ = ~1'h0;
  assign _115_ = ~_013_;
  assign _199_ = ~1'h0;
  assign f0 = ~_219_;
  assign \[0]  = r;
  assign \[10]  = 1'h0;
  assign \[11]  = c0;
  assign \[12]  = d0;
  assign \[13]  = e0;
  assign \[14]  = f0;
  assign \[15]  = g0;
  assign \[16]  = h0;
  assign \[17]  = i0;
  assign \[18]  = j0;
  assign \[19]  = k0;
  assign \[1]  = s;
  assign \[20]  = l0;
  assign \[21]  = m0;
  assign \[22]  = n0;
  assign \[23]  = o0;
  assign \[24]  = p0;
  assign \[25]  = q0;
  assign \[26]  = r0;
  assign \[27]  = s0;
  assign \[28]  = t0;
  assign \[29]  = u0;
  assign \[2]  = t;
  assign \[30]  = v0;
  assign \[31]  = w0;
  assign \[32]  = x0;
  assign \[33]  = y0;
  assign \[34]  = 1'h0;
  assign \[35]  = a1;
  assign \[36]  = 1'h0;
  assign \[37]  = c1;
  assign \[38]  = d1;
  assign \[3]  = u;
  assign \[4]  = v;
  assign \[5]  = t;
  assign \[6]  = t;
  assign \[7]  = y;
  assign \[8]  = z;
  assign \[9]  = a0;
  assign b0 = 1'h0;
  assign b1 = 1'h0;
  assign w = t;
  assign x = t;
  assign z0 = 1'h0;
endmodule
