/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 8.3.0-6 -fPIC -Os) */

(* src = "LGSynt91/t481_orig.v:2" *)
(* top =  1  *)
module t481(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, \v16.0 );
  (* src = "LGSynt91/t481_orig.v:22" *)
  wire \[0] ;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v0;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v1;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v10;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v11;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v12;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v13;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v14;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v15;
  (* src = "LGSynt91/t481_orig.v:20" *)
  output \v16.0 ;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v2;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v3;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v4;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v5;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v6;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v7;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v8;
  (* src = "LGSynt91/t481_orig.v:3" *)
  input v9;
  assign \v16.0  = ~1'h0;
  assign \[0]  = \v16.0 ;
endmodule
